MLIR: lib/Conversion/AsyncToLLVM/AsyncToLLVM.cpp File Reference
AsyncToLLVM.cpp File Reference
#include "mlir/Conversion/AsyncToLLVM/AsyncToLLVM.h"
#include "../PassDetail.h"
#include "mlir/Dialect/Async/IR/Async.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/RegionUtils.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/FormatVariadic.h"
Macros
#define DEBUG_TYPE "convert-async-to-llvm"
Functions
static void addAsyncRuntimeApiDeclarations (ModuleOp module)
static void addCoroutineIntrinsicsDeclarations (ModuleOp module)
Adds coroutine intrinsics declarations to the module.
static void addCRuntimeDeclarations (ModuleOp module)
Adds malloc/free declarations to the module.
static void addResumeFunction (ModuleOp module)
static CoroMachinery setupCoroMachinery (FuncOp func)
static Block * addSuspensionPoint (CoroMachinery coro, Value coroState, Operation *op)
static std::pair< FuncOp, CoroMachinery > outlineExecuteOp (SymbolTable &symbolTable, ExecuteOp execute)
Variables
static constexpr const char kAsyncFnPrefix [] = "async_execute_fn"
static constexpr const char * kCreateToken = "mlirAsyncRuntimeCreateToken"
static constexpr const char * kEmplaceToken = "mlirAsyncRuntimeEmplaceToken"
static constexpr const char * kAwaitToken = "mlirAsyncRuntimeAwaitToken"
static constexpr const char * kExecute = "mlirAsyncRuntimeExecute"
static constexpr const char * kAwaitAndExecute
static constexpr const char * kCoroId = "llvm.coro.id"
static constexpr const char * kCoroSizeI64 = "llvm.coro.size.i64"
static constexpr const char * kCoroBegin = "llvm.coro.begin"
static constexpr const char * kCoroSave = "llvm.coro.save"
static constexpr const char * kCoroSuspend = "llvm.coro.suspend"
static constexpr const char * kCoroEnd = "llvm.coro.end"
static constexpr const char * kCoroFree = "llvm.coro.free"
static constexpr const char * kCoroResume = "llvm.coro.resume"
static constexpr const char * kMalloc = "malloc"
static constexpr const char * kFree = "free"
static constexpr const char * kResume = "__resume"
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "convert-async-to-llvm"
Definition at line 24 of file AsyncToLLVM.cpp.
Function Documentation
addAsyncRuntimeApiDeclarations()
static void addAsyncRuntimeApiDeclarations (ModuleOp module) static
Definition at line 80 of file AsyncToLLVM.cpp.
References mlir::OpBuilder::atBlockTerminator(), mlir::FuncOp::create(), mlir::ModuleOp::getBody(), mlir::OpState::getContext(), mlir::OpState::getLoc(), kAwaitAndExecute, kAwaitToken, kCreateToken, kEmplaceToken, and kExecute.
Referenced by outlineExecuteOp().
addCoroutineIntrinsicsDeclarations()
static void addCoroutineIntrinsicsDeclarations (ModuleOp module) static
Adds coroutine intrinsics declarations to the module.
Definition at line 120 of file AsyncToLLVM.cpp.
References mlir::ModuleOp::getBody(), mlir::OpState::getContext(), mlir::OpState::getLoc(), mlir::Block::getTerminator(), kCoroBegin, kCoroEnd, kCoroFree, kCoroId, kCoroResume, kCoroSave, kCoroSizeI64, and kCoroSuspend.
Referenced by outlineExecuteOp().
addCRuntimeDeclarations()
static void addCRuntimeDeclarations (ModuleOp module) static
Adds malloc/free declarations to the module.
Definition at line 179 of file AsyncToLLVM.cpp.
References mlir::ModuleOp::getBody(), mlir::OpState::getContext(), mlir::OpState::getLoc(), mlir::Block::getTerminator(), kFree, and kMalloc.
Referenced by outlineExecuteOp().
addResumeFunction()
static void addResumeFunction (ModuleOp module) static
Definition at line 209 of file AsyncToLLVM.cpp.
References mlir::OpBuilder::atBlockEnd(), mlir::OpBuilder::create(), mlir::LLVM::LLVMFunctionType::get(), mlir::ModuleOp::getBody(), mlir::OpState::getContext(), mlir::LLVM::LLVMType::getInt8PtrTy(), mlir::OpState::getLoc(), mlir::Builder::getSymbolRefAttr(), mlir::Block::getTerminator(), mlir::LLVM::LLVMType::getVoidTy(), kCoroResume, kResume, mlir::SymbolTable::Private, and mlir::SymbolTable::setSymbolVisibility().
Referenced by outlineExecuteOp().
addSuspensionPoint()
static Block* addSuspensionPoint (CoroMachinery coro, Value coroState, Operation * op) static
Definition at line 404 of file AsyncToLLVM.cpp.
References mlir::OpBuilder::atBlockEnd(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::edsc::op::eq(), mlir::Operation::getBlock(), mlir::Builder::getBoolAttr(), mlir::Operation::getContext(), mlir::Builder::getI8IntegerAttr(), mlir::LLVM::LLVMType::getInt1Ty(), mlir::LLVM::LLVMType::getInt8Ty(), mlir::Operation::getLoc(), mlir::Builder::getSymbolRefAttr(), isZero(), kCoroSuspend, mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::Block::splitBlock().
Referenced by outlineExecuteOp().
outlineExecuteOp()
static std::pair<FuncOp, CoroMachinery> outlineExecuteOp (SymbolTable & symbolTable, ExecuteOp execute) static
Definition at line 457 of file AsyncToLLVM.cpp.
References addAsyncRuntimeApiDeclarations(), addCoroutineIntrinsicsDeclarations(), addCRuntimeDeclarations(), addResumeFunction(), addSuspensionPoint(), mlir::WalkResult::advance(), mlir::applyPartialConversion(), mlir::OpBuilder::atBlockTerminator(), mlir::OpBuilder::clone(), mlir::FuncOp::create(), mlir::PatternRewriter::create(), mlir::OpBuilder::create(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), mlir::ModuleOp::getBody(), mlir::Operation::getContext(), mlir::Type::getContext(), mlir::OpState::getContext(), mlir::LLVM::LLVMType::getInt8PtrTy(), mlir::Operation::getLoc(), mlir::Operation::getOperand(), mlir::OpState::getParentOfType(), mlir::Operation::getResultTypes(), mlir::Builder::getSymbolRefAttr(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::getUsedValuesDefinedAbove(), mlir::SymbolTable::insert(), mlir::OwningRewritePatternList::insert(), mlir::WalkResult::interrupt(), mlir::Type::isa(), kAsyncFnPrefix, kAwaitAndExecute, kAwaitToken, kCoroSave, kEmplaceToken, kExecute, kResume, mlir::BlockAndValueMapping::map(), mlir::populateFuncOpTypeConversionPattern(), mlir::SymbolTable::Private, mlir::PatternRewriter::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPointToStart(), mlir::SymbolTable::setSymbolVisibility(), setupCoroMachinery(), mlir::success(), mlir::OpState::walk(), and mlir::WalkResult::wasInterrupted().
setupCoroMachinery()
static CoroMachinery setupCoroMachinery (FuncOp func) static
Definition at line 282 of file AsyncToLLVM.cpp.
References mlir::OpBuilder::atBlockBegin(), mlir::OpBuilder::create(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get(), mlir::Builder::getBoolAttr(), mlir::OpState::getContext(), mlir::Builder::getI32IntegerAttr(), mlir::LLVM::LLVMType::getInt1Ty(), mlir::LLVM::LLVMType::getInt32Ty(), mlir::LLVM::LLVMType::getInt64Ty(), mlir::LLVM::LLVMType::getInt8PtrTy(), mlir::OpState::getLoc(), mlir::Builder::getSymbolRefAttr(), kCoroBegin, kCoroEnd, kCoroFree, kCoroId, kCoroSizeI64, kCreateToken, kFree, kMalloc, mlir::OpBuilder::setInsertionPointToEnd(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by outlineExecuteOp().
Variable Documentation
kAsyncFnPrefix
constexpr const char kAsyncFnPrefix[] = "async_execute_fn" static
Definition at line 30 of file AsyncToLLVM.cpp.
Referenced by outlineExecuteOp().
kAwaitAndExecute
constexpr const char* kAwaitAndExecute static
Initial value:
=
    "mlirAsyncRuntimeAwaitTokenAndExecute"
Definition at line 40 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kAwaitToken
constexpr const char* kAwaitToken = "mlirAsyncRuntimeAwaitToken" static
Definition at line 38 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kCoroBegin
constexpr const char* kCoroBegin = "llvm.coro.begin" static
Definition at line 112 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and setupCoroMachinery().
kCoroEnd
constexpr const char* kCoroEnd = "llvm.coro.end" static
Definition at line 115 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and setupCoroMachinery().
kCoroFree
constexpr const char* kCoroFree = "llvm.coro.free" static
Definition at line 116 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and setupCoroMachinery().
kCoroId
constexpr const char* kCoroId = "llvm.coro.id" static
Definition at line 110 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and setupCoroMachinery().
kCoroResume
constexpr const char* kCoroResume = "llvm.coro.resume" static
Definition at line 117 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and addResumeFunction().
kCoroSave
constexpr const char* kCoroSave = "llvm.coro.save" static
Definition at line 113 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and outlineExecuteOp().
kCoroSizeI64
constexpr const char* kCoroSizeI64 = "llvm.coro.size.i64" static
Definition at line 111 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and setupCoroMachinery().
kCoroSuspend
constexpr const char* kCoroSuspend = "llvm.coro.suspend" static
Definition at line 114 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and addSuspensionPoint().
kCreateToken
constexpr const char* kCreateToken = "mlirAsyncRuntimeCreateToken" static
Definition at line 36 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and setupCoroMachinery().
kEmplaceToken
constexpr const char* kEmplaceToken = "mlirAsyncRuntimeEmplaceToken" static
Definition at line 37 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kExecute
constexpr const char* kExecute = "mlirAsyncRuntimeExecute" static
Definition at line 39 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kFree
constexpr const char* kFree = "free" static
Definition at line 176 of file AsyncToLLVM.cpp.
Referenced by addCRuntimeDeclarations(), and setupCoroMachinery().
kMalloc
constexpr const char* kMalloc = "malloc" static
Definition at line 175 of file AsyncToLLVM.cpp.
Referenced by addCRuntimeDeclarations(), and setupCoroMachinery().
kResume
constexpr const char* kResume = "__resume" static
Definition at line 204 of file AsyncToLLVM.cpp.
Referenced by addResumeFunction(), and outlineExecuteOp().