MLIR: include/mlir-c/Diagnostics.h File Reference
Diagnostics.h File Reference
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
Classes
struct MlirDiagnostic
An opaque reference to a dignostic, always owned by the diagnostics engine (context).
Typedefs
typedef struct MlirDiagnostic MlirDiagnostic
typedef enum MlirDiagnosticSeverity MlirDiagnosticSeverity
typedef uint64_t MlirDiagnosticHandlerID
Opaque identifier of a diagnostic handler, useful to detach a handler.
typedef MlirLogicalResult(* MlirDiagnosticHandler) (MlirDiagnostic)
Diagnostic handler type.
Enumerations
enum MlirDiagnosticSeverity { MlirDiagnosticError, MlirDiagnosticWarning, MlirDiagnosticNote, MlirDiagnosticRemark }
Severity of a diagnostic.
Functions
void mlirDiagnosticPrint (MlirDiagnostic diagnostic, MlirStringCallback callback, void *userData)
Prints a diagnostic using the provided callback.
MlirLocation mlirDiagnosticGetLocation (MlirDiagnostic diagnostic)
Returns the location at which the diagnostic is reported.
MlirDiagnosticSeverity mlirDiagnosticGetSeverity (MlirDiagnostic diagnostic)
Returns the severity of the diagnostic.
intptr_t mlirDiagnosticGetNumNotes (MlirDiagnostic diagnostic)
Returns the number of notes attached to the diagnostic.
MlirDiagnostic mlirDiagnosticGetNote (MlirDiagnostic diagnostic, intptr_t pos)
Returns pos-th note attached to the diagnostic.
MlirDiagnosticHandlerID mlirContextAttachDiagnosticHandler (MlirContext context, MlirDiagnosticHandler handler)
Attaches the diagnostic handler to the context.
void mlirContextDetachDiagnosticHandler (MlirContext context, MlirDiagnosticHandlerID id)
Detaches an attached diagnostic handler from the context given its identifier.
void mlirEmitError (MlirLocation location, const char *message)
Emits an error at the given location through the diagnostics engine.
Typedef Documentation
MlirDiagnostic
typedef struct MlirDiagnostic MlirDiagnostic
Definition at line 29 of file Diagnostics.h.
MlirDiagnosticHandler
typedef MlirLogicalResult(* MlirDiagnosticHandler) (MlirDiagnostic)
Diagnostic handler type.
Acceps a reference to a diagnostic, which is only guaranteed to be live during the call. If the handler processed the diagnostic completely, it is expected to return success. Otherwise, it is expected to return failure to indicate that other handlers should attempt to process the diagnostic.
Definition at line 48 of file Diagnostics.h.
MlirDiagnosticHandlerID
typedef uint64_t MlirDiagnosticHandlerID
Opaque identifier of a diagnostic handler, useful to detach a handler.
Definition at line 41 of file Diagnostics.h.
MlirDiagnosticSeverity
typedef enum MlirDiagnosticSeverity MlirDiagnosticSeverity
Definition at line 38 of file Diagnostics.h.
Enumeration Type Documentation
MlirDiagnosticSeverity
enum MlirDiagnosticSeverity
Severity of a diagnostic.
Enumerator
MlirDiagnosticError
MlirDiagnosticWarning
MlirDiagnosticNote
MlirDiagnosticRemark
Definition at line 32 of file Diagnostics.h.
Function Documentation
mlirContextAttachDiagnosticHandler()
MlirDiagnosticHandlerID mlirContextAttachDiagnosticHandler (MlirContext context, MlirDiagnosticHandler handler)
Attaches the diagnostic handler to the context.
Handlers are invoked in the reverse order of attachment until one of them processes the diagnostic completely. Returns an identifier that can be used to detach the handler.
Definition at line 56 of file Diagnostics.cpp.
References unwrap(), and wrap().
mlirContextDetachDiagnosticHandler()
void mlirContextDetachDiagnosticHandler (MlirContext context, MlirDiagnosticHandlerID id)
Detaches an attached diagnostic handler from the context given its identifier.
Definition at line 67 of file Diagnostics.cpp.
References unwrap().
mlirDiagnosticGetLocation()
MlirLocation mlirDiagnosticGetLocation (MlirDiagnostic diagnostic)
Returns the location at which the diagnostic is reported.
Definition at line 25 of file Diagnostics.cpp.
References unwrap(), and wrap().
mlirDiagnosticGetNote()
MlirDiagnostic mlirDiagnosticGetNote (MlirDiagnostic diagnostic, intptr_t pos)
Returns pos-th note attached to the diagnostic.
Expects pos to be a valid zero-based index into the list of notes.
Definition at line 51 of file Diagnostics.cpp.
References unwrap(), and wrap().
mlirDiagnosticGetNumNotes()
intptr_t mlirDiagnosticGetNumNotes (MlirDiagnostic diagnostic)
Returns the number of notes attached to the diagnostic.
Definition at line 45 of file Diagnostics.cpp.
References unwrap().
mlirDiagnosticGetSeverity()
MlirDiagnosticSeverity mlirDiagnosticGetSeverity (MlirDiagnostic diagnostic)
Returns the severity of the diagnostic.
Definition at line 29 of file Diagnostics.cpp.
References mlir::Error, MlirDiagnosticError, MlirDiagnosticNote, MlirDiagnosticRemark, MlirDiagnosticWarning, mlir::Note, mlir::Remark, unwrap(), and mlir::Warning.
mlirDiagnosticPrint()
void mlirDiagnosticPrint (MlirDiagnostic diagnostic, MlirStringCallback callback, void * userData)
Prints a diagnostic using the provided callback.
Definition at line 18 of file Diagnostics.cpp.
References mlir::Diagnostic::print(), and unwrap().
mlirEmitError()
void mlirEmitError (MlirLocation location, const char * message)
Emits an error at the given location through the diagnostics engine.
Used for testing purposes.
Definition at line 73 of file Diagnostics.cpp.
References mlir::emitError(), and unwrap().