MLIR: include/mlir-c/Support.h File Reference
Support.h File Reference
#include <stddef.h>
#include <stdint.h>
Classes
struct MlirStringRef
A pointer to a sized fragment of a string, not necessarily null-terminated.
struct MlirLogicalResult
A logical result value, essentially a boolean with named states.
Typedefs
typedef struct MlirStringRef MlirStringRef
typedef struct MlirLogicalResult MlirLogicalResult
Functions
MlirStringRef mlirStringRefCreate (const char *str, size_t length)
Constructs a string reference from the pointer and length.
MlirStringRef mlirStringRefCreateFromCString (const char *str)
Constructs a string reference from a null-terminated C string.
int mlirLogicalResultIsSuccess (MlirLogicalResult res)
Checks if the given logical result represents a success.
int mlirLogicalResultIsFailure (MlirLogicalResult res)
Checks if the given logical result represents a failure.
static MlirLogicalResult mlirLogicalResultSuccess ()
Creates a logical result representing a success.
static MlirLogicalResult mlirLogicalResultFailure ()
Creates a logical result representing a failure.
Typedef Documentation
MlirLogicalResult
typedef struct MlirLogicalResult MlirLogicalResult
Definition at line 65 of file Support.h.
MlirStringRef
typedef struct MlirStringRef MlirStringRef
Definition at line 36 of file Support.h.
Function Documentation
mlirLogicalResultFailure()
static MlirLogicalResult mlirLogicalResultFailure () inline static
Creates a logical result representing a failure.
Definition at line 84 of file Support.h.
Referenced by wrap().
mlirLogicalResultIsFailure()
int mlirLogicalResultIsFailure (MlirLogicalResult res) inline
Checks if the given logical result represents a failure.
Definition at line 73 of file Support.h.
References MlirLogicalResult::value.
mlirLogicalResultIsSuccess()
int mlirLogicalResultIsSuccess (MlirLogicalResult res) inline
Checks if the given logical result represents a success.
Definition at line 68 of file Support.h.
References MlirLogicalResult::value.
Referenced by unwrap().
mlirLogicalResultSuccess()
static MlirLogicalResult mlirLogicalResultSuccess () inline static
Creates a logical result representing a success.
Definition at line 78 of file Support.h.
Referenced by wrap().
mlirStringRefCreate()
MlirStringRef mlirStringRefCreate (const char * str, size_t length) inline
Constructs a string reference from the pointer and length.
The pointer need not reference to a null-terminated string.
Definition at line 41 of file Support.h.
References MlirStringRef::data, MlirStringRef::length, and mlirStringRefCreateFromCString().
Referenced by mlirStringRefCreateFromCString(), and wrap().
mlirStringRefCreateFromCString()
MlirStringRef mlirStringRefCreateFromCString (const char * str)
Constructs a string reference from a null-terminated C string.
Prefer mlirStringRefCreate if the length of the string is known.
Definition at line 13 of file Support.cpp.
References mlirStringRefCreate().
Referenced by mlirStringRefCreate().