MLIR: mlir::python::PyType Class Reference
mlir::python::PyType Class Reference
Wrapper around the generic MlirType.
#include "Bindings/Python/IRModules.h"
Public Member Functions
PyType (PyMlirContextRef contextRef, MlirType type)
bool operator== (const PyType &other)
operator MlirType () const
Public Member Functions inherited from mlir::python::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Public Attributes
MlirType type
Detailed Description
Wrapper around the generic MlirType.
The lifetime of a type is bound by the PyContext that created it.
Definition at line 384 of file IRModules.h.
Constructor & Destructor Documentation
PyType()
mlir::python::PyType::PyType (PyMlirContextRef contextRef, MlirType type) inline
Definition at line 386 of file IRModules.h.
References mlir::operator==().
Member Function Documentation
operator MlirType()
mlir::python::PyType::operator MlirType () const inline
Definition at line 389 of file IRModules.h.
operator==()
bool PyType::operator== (const PyType & other)
Definition at line 839 of file IRModules.cpp.
References mlir::python::PyAttribute::attr, MlirNamedAttribute::attribute, mlir::python::PyOperation::checkValid(), mlir::python::PyMlirContext::createFromCapsule(), mlir::python::PyModule::createFromCapsule(), mlir::python::PyMlirContext::createNewContextForInit(), mlir::python::PyMlirContext::createOperation(), MlirStringRef::data, mlir::python::PyMlirContext::forContext(), mlir::python::PyModule::forModule(), mlir::python::PyOperation::forOperation(), mlir::python::PyMlirContext::get(), mlir::python::PyOperation::get(), mlir::python::PyRegion::get(), mlir::python::PyBlock::get(), mlir::python::PyValue::get(), mlir::python::PyOperation::getAsm(), mlir::python::PyMlirContext::getCapsule(), mlir::python::PyModule::getCapsule(), mlir::python::BaseContextObject::getContext(), mlir::python::PyMlirContext::getLiveCount(), mlir::python::PyMlirContext::getLiveModuleCount(), mlir::python::PyMlirContext::getLiveOperationCount(), mlir::python::PyValue::getParentOperation(), mlir::python::PyMlirContext::getRef(), kContextCreateOperationDocstring, kContextGetFileLocationDocstring, kContextGetUnknownLocationDocstring, kContextParseDocstring, kContextParseTypeDocstring, kDumpDocstring, kOperationGetAsmDocstring, kOperationPrintDocstring, kOperationStrDunderDocstring, kValueDunderStrDocstring, MlirStringRef::length, mlir::python::PyLocation::loc, MLIR_PYTHON_CAPI_FACTORY_ATTR, MLIR_PYTHON_CAPI_PTR_ATTR, mlirAttributeDump(), mlirAttributeGetContext(), mlirAttributeGetType(), mlirAttributeIsABool(), mlirAttributeIsADenseElements(), mlirAttributeIsAFloat(), mlirAttributeIsAInteger(), mlirAttributeIsAString(), mlirAttributeIsNull(), mlirAttributeParseGet(), mlirAttributePrint(), mlirBF16TypeGet(), mlirBlockArgumentGetArgNumber(), mlirBlockArgumentGetOwner(), mlirBlockArgumentSetType(), mlirBlockGetArgument(), mlirBlockGetFirstOperation(), mlirBlockGetNumArguments(), mlirBlockPrint(), mlirBoolAttrGet(), mlirBoolAttrGetValue(), mlirComplexTypeGetElementType(), mlirContextGetAllowUnregisteredDialects(), mlirContextSetAllowUnregisteredDialects(), mlirDenseElementsAttrDoubleGet(), mlirDenseElementsAttrFloatGet(), mlirDenseElementsAttrInt32Get(), mlirDenseElementsAttrInt64Get(), mlirDenseElementsAttrIsSplat(), mlirDenseElementsAttrSplatGet(), mlirDenseElementsAttrUInt32Get(), mlirDenseElementsAttrUInt64Get(), mlirF16TypeGet(), mlirF32TypeGet(), mlirF64TypeGet(), mlirFloatAttrDoubleGet(), mlirFloatAttrDoubleGetChecked(), mlirFloatAttrGetValueDouble(), mlirFunctionTypeGet(), mlirFunctionTypeGetInput(), mlirFunctionTypeGetNumInputs(), mlirFunctionTypeGetNumResults(), mlirFunctionTypeGetResult(), mlirIndexTypeGet(), mlirIntegerAttrGet(), mlirIntegerAttrGetValueInt(), mlirIntegerTypeGet(), mlirIntegerTypeGetWidth(), mlirIntegerTypeIsSigned(), mlirIntegerTypeIsSignless(), mlirIntegerTypeIsUnsigned(), mlirIntegerTypeSignedGet(), mlirIntegerTypeUnsignedGet(), mlirLocationFileLineColGet(), mlirLocationPrint(), mlirLocationUnknownGet(), mlirMemRefTypeContiguousGetChecked(), mlirMemRefTypeGetMemorySpace(), mlirMemRefTypeGetNumAffineMaps(), mlirModuleCreateEmpty(), mlirModuleCreateParse(), mlirModuleGetOperation(), mlirModuleIsNull(), mlirNoneTypeGet(), mlirOperationDump(), mlirOperationEqual(), mlirOperationGetNumResults(), mlirOperationGetResult(), mlirOperationPrint(), mlirOpResultGetOwner(), mlirOpResultGetResultNumber(), mlirRankedTensorTypeGet(), mlirRankedTensorTypeGetChecked(), mlirRegionGetFirstBlock(), mlirShapedTypeGetDimSize(), mlirShapedTypeGetElementType(), mlirShapedTypeGetRank(), mlirShapedTypeHasRank(), mlirShapedTypeHasStaticShape(), mlirShapedTypeIsDynamicDim(), mlirShapedTypeIsDynamicSize(), mlirShapedTypeIsDynamicStrideOrOffset(), mlirStringAttrGet(), mlirStringAttrGetValue(), mlirStringAttrTypedGet(), mlirTupleTypeGet(), mlirTupleTypeGetNumTypes(), mlirTupleTypeGetType(), mlirTypeDump(), mlirTypeEqual(), mlirTypeGetContext(), mlirTypeIsABF16(), mlirTypeIsAComplex(), mlirTypeIsAF16(), mlirTypeIsAF32(), mlirTypeIsAF64(), mlirTypeIsAFunction(), mlirTypeIsAIndex(), mlirTypeIsAInteger(), mlirTypeIsANone(), mlirTypeIsARankedTensor(), mlirTypeIsAShaped(), mlirTypeIsATuple(), mlirTypeIsAUnrankedMemRef(), mlirTypeIsAUnrankedTensor(), mlirTypeIsAVector(), mlirTypeIsNull(), mlirTypeParseGet(), mlirTypePrint(), mlirUnrankedMemrefGetMemorySpace(), mlirUnrankedMemRefTypeGetChecked(), mlirUnrankedTensorTypeGetChecked(), mlirValueDump(), mlirValueGetType(), mlirValueIsABlockArgument(), mlirValueIsAOpResult(), mlirValuePrint(), mlirVectorTypeGetChecked(), MlirNamedAttribute::name, mlir::python::PyNamedAttribute::namedAttr, mlir::python::populateIRSubmodule(), mlir::python::PyOperation::print(), mlir::python::PyNamedAttribute::PyNamedAttribute(), mlir::python::PyObjectRef< T >::releaseObject(), mlir::python::SetPyError(), and type.
Member Data Documentation
type
MlirType mlir::python::PyType::type
Definition at line 391 of file IRModules.h.
Referenced by operator==().
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModules.h
lib/Bindings/Python/IRModules.cpp