MLIR: mlir::linalg::TensorConstantOpConverter Class Reference
mlir::linalg::TensorConstantOpConverter Class Reference
TensorConstantOp conversion inserts a linearized 1-D vector constant that is stored in memory.
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
Public Member Functions
LogicalResult matchAndRewrite (ConstantOp op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const final
Public Member Functions inherited from mlir::BufferizeOpConversionPattern< ConstantOp >
BufferizeOpConversionPattern (MLIRContext *context, BufferizeTypeConverter &converter, PatternBenefit benefit=1)
Public Member Functions inherited from mlir::OpConversionPattern< ConstantOp >
OpConversionPattern (MLIRContext *context, PatternBenefit benefit=1)
OpConversionPattern (TypeConverter &typeConverter, MLIRContext *context, PatternBenefit benefit=1)
void rewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const final
Wrappers around the ConversionPattern methods that pass the derived op type.
virtual void rewrite (ConstantOp op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Rewrite and Match methods that operate on the SourceOp type.
LogicalResult matchAndRewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const final
Hook for derived classes to implement combined matching and rewriting.
Public Member Functions inherited from mlir::ConversionPattern
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match and rewrite the IR root at the specified operation.
TypeConverter * getTypeConverter () const
Return the type converter held by this pattern, or nullptr if the pattern does not require type conversion.
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
virtual LogicalResult match (Operation *op) const
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
Additional Inherited Members
Protected Member Functions inherited from mlir::ConversionPattern
ConversionPattern (StringRef rootName, PatternBenefit benefit, TypeConverter &typeConverter, MLIRContext *ctx)
Construct a conversion pattern that matches an operation with the given root name.
ConversionPattern (PatternBenefit benefit, TypeConverter &typeConverter, MatchAnyOpTypeTag tag)
Construct a conversion pattern that matches any operation type.
Protected Member Functions inherited from mlir::RewritePattern
virtual void anchor ()
An anchor for the virtual table.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a pattern with a certain benefit that matches any operation type.
Pattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a pattern that may match any operation type.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Protected Attributes inherited from mlir::BufferizeOpConversionPattern< ConstantOp >
BufferizeTypeConverter & converter
Protected Attributes inherited from mlir::ConversionPattern
TypeConverter * typeConverter = nullptr
An optional type converter for use by this pattern.
Detailed Description
TensorConstantOp conversion inserts a linearized 1-D vector constant that is stored in memory.
A linalg.reshape is introduced to convert to the desired n-D buffer form.
Definition at line 820 of file Transforms.h.
Member Function Documentation
matchAndRewrite()
LogicalResult mlir::linalg::TensorConstantOpConverter::matchAndRewrite (ConstantOp op, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) const final virtual
Reimplemented from mlir::OpConversionPattern< ConstantOp >.
Definition at line 233 of file Bufferize.cpp.
References mlir::BufferizeConversionPattern::converter, mlir::TypeConverter::convertType(), mlir::PatternRewriter::create(), mlir::failure(), mlir::VectorType::get(), mlir::MemRefType::get(), mlir::Builder::getAffineMapArrayAttr(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::RankedTensorType::getShape(), mlir::ShapedType::isDynamic(), mlir::ConversionPatternRewriter::replaceOp(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Linalg/Transforms/Transforms.h
lib/Dialect/Linalg/Transforms/Bufferize.cpp