MLIR: mlir::BufferPlacementTransformationBase Class Reference
mlir::BufferPlacementTransformationBase Class Reference
The base class for all BufferPlacement transformations.
#include "mlir/Transforms/Bufferize.h"
Public Types
using ValueSetT = BufferAliasAnalysis::ValueSetT
Public Member Functions
BufferPlacementTransformationBase (Operation *op)
Constructs a new operation base using the given root operation.
Static Public Member Functions
template<typename DominatorT >
static Block * findCommonDominator (Value value, const ValueSetT &values, const DominatorT &doms)
Finds a common dominator for the given value while taking the positions of the values in the value set into account.
static bool isLoop (Operation *op)
Returns true if the given operation represents a loop by testing whether it implements the LoopLikeOpInterface or the RegionBranchOpInterface.
Protected Attributes
BufferAliasAnalysis aliases
Alias information that can be updated during the insertion of copies.
BufferPlacementAllocs allocs
Stores all internally managed allocations.
Liveness liveness
The underlying liveness analysis to compute fine grained information about alloc and dealloc positions.
Detailed Description
The base class for all BufferPlacement transformations.
Definition at line 340 of file Bufferize.h.
Member Typedef Documentation
ValueSetT
using mlir::BufferPlacementTransformationBase::ValueSetT = BufferAliasAnalysis::ValueSetT
Definition at line 342 of file Bufferize.h.
Constructor & Destructor Documentation
BufferPlacementTransformationBase()
BufferPlacementTransformationBase::BufferPlacementTransformationBase (Operation * op)
Constructs a new operation base using the given root operation.
Constructs a new transformation base using the given root operation.
Definition at line 176 of file BufferDeallocation.cpp.
Referenced by isLoop().
Member Function Documentation
findCommonDominator()
template<typename DominatorT > static Block* mlir::BufferPlacementTransformationBase::findCommonDominator (Value value, const ValueSetT & values, const DominatorT & doms) inline static
Finds a common dominator for the given value while taking the positions of the values in the value set into account.
It supports dominator and post-dominator analyses via template arguments.
Definition at line 348 of file Bufferize.h.
References mlir::Value::getParentBlock(), and mlir::Operation::getUsers().
Referenced by isLoop().
isLoop()
bool BufferPlacementTransformationBase::isLoop (Operation * op) static
Returns true if the given operation represents a loop by testing whether it implements the LoopLikeOpInterface or the RegionBranchOpInterface.
In the case of a RegionBranchOpInterface, it checks all region-based control-flow edges for cycles.
In the case of a RegionBranchOpInterface, it checks all region-based control- flow edges for cycles.
Definition at line 184 of file BufferDeallocation.cpp.
References aliases, allocs, BufferPlacementTransformationBase(), mlir::Type::cast(), copy(), mlir::OpBuilder::create(), mlir::Operation::emitError(), mlir::BufferAliasAnalysis::end(), mlir::detail::enumerate(), mlir::BufferAliasAnalysis::find(), findCommonDominator(), mlir::Region::front(), mlir::BlockArgument::getArgNumber(), mlir::Operation::getBlock(), mlir::Value::getDefiningOp(), mlir::LivenessBlockInfo::getEndOperation(), mlir::Liveness::getLiveness(), mlir::Operation::getLoc(), mlir::Value::getLoc(), mlir::Operation::getOperand(), mlir::Operation::getOperands(), mlir::Block::getOperations(), mlir::BlockArgument::getOwner(), mlir::Block::getParent(), mlir::Value::getParentBlock(), mlir::Region::getParentOp(), mlir::Region::getRegionNumber(), mlir::Operation::getRegions(), mlir::RegionSuccessor::getSuccessor(), mlir::Operation::getSuccessor(), getSuccessorRegions(), mlir::Block::getSuccessors(), mlir::Value::getType(), mlir::Value::isa(), mlir::Operation::isBeforeInBlock(), mlir::ShapedType::isDynamic(), liveness, mlir::Operation::moveAfter(), mlir::Block::pred_begin(), mlir::Block::pred_end(), mlir::BufferAliasAnalysis::remove(), mlir::BufferAliasAnalysis::resolve(), mlir::Operation::setOperand(), and walkReturnOperations().
Referenced by hasAllocationScope().
Member Data Documentation
aliases
BufferAliasAnalysis mlir::BufferPlacementTransformationBase::aliases protected
Alias information that can be updated during the insertion of copies.
Definition at line 377 of file Bufferize.h.
Referenced by isLoop().
allocs
BufferPlacementAllocs mlir::BufferPlacementTransformationBase::allocs protected
Stores all internally managed allocations.
Definition at line 380 of file Bufferize.h.
Referenced by isLoop().
liveness
Liveness mlir::BufferPlacementTransformationBase::liveness protected
The underlying liveness analysis to compute fine grained information about alloc and dealloc positions.
Definition at line 384 of file Bufferize.h.
Referenced by isLoop().
The documentation for this class was generated from the following files:
include/mlir/Transforms/Bufferize.h
lib/Transforms/BufferDeallocation.cpp