MLIR: lib/Conversion/VectorToLLVM/ConvertVectorToLLVM.cpp File Reference
ConvertVectorToLLVM.cpp File Reference
#include "mlir/Conversion/VectorToLLVM/ConvertVectorToLLVM.h"
#include "../PassDetail.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVMPass.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/Target/LLVMIR/TypeTranslation.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/ErrorHandling.h"
Functions
static VectorType reducedVectorTypeFront (VectorType tp)
static VectorType reducedVectorTypeBack (VectorType tp)
static Value insertOne (ConversionPatternRewriter &rewriter, LLVMTypeConverter &typeConverter, Location loc, Value val1, Value val2, Type llvmType, int64_t rank, int64_t pos)
static Value insertOne (PatternRewriter &rewriter, Location loc, Value from, Value into, int64_t offset)
static Value extractOne (ConversionPatternRewriter &rewriter, LLVMTypeConverter &typeConverter, Location loc, Value val, Type llvmType, int64_t rank, int64_t pos)
static Value extractOne (PatternRewriter &rewriter, Location loc, Value vector, int64_t offset)
static SmallVector< int64_t, 4 > getI64SubArray (ArrayAttr arrayAttr, unsigned dropFront=0, unsigned dropBack=0)
static Value buildVectorComparison (ConversionPatternRewriter &rewriter, Operation *op, bool enableIndexOptimizations, int64_t dim, Value b, Value *off=nullptr)
template<typename T >
LogicalResult getMemRefAlignment (LLVMTypeConverter &typeConverter, T op, unsigned &align)
static LogicalResult getBase (ConversionPatternRewriter &rewriter, Location loc, Value memref, MemRefType memRefType, Value &base)
static LogicalResult getBasePtr (ConversionPatternRewriter &rewriter, Location loc, Value memref, MemRefType memRefType, Value &ptr)
static LogicalResult getBasePtr (ConversionPatternRewriter &rewriter, Location loc, Value memref, MemRefType memRefType, Type type, Value &ptr)
static LogicalResult getIndexedPtrs (ConversionPatternRewriter &rewriter, Location loc, Value memref, Value indices, MemRefType memRefType, VectorType vType, Type iType, Value &ptrs)
static LogicalResult replaceTransferOpWithLoadOrStore (ConversionPatternRewriter &rewriter, LLVMTypeConverter &typeConverter, Location loc, TransferReadOp xferOp, ArrayRef< Value > operands, Value dataPtr)
static LogicalResult replaceTransferOpWithMasked (ConversionPatternRewriter &rewriter, LLVMTypeConverter &typeConverter, Location loc, TransferReadOp xferOp, ArrayRef< Value > operands, Value dataPtr, Value mask)
static LogicalResult replaceTransferOpWithLoadOrStore (ConversionPatternRewriter &rewriter, LLVMTypeConverter &typeConverter, Location loc, TransferWriteOp xferOp, ArrayRef< Value > operands, Value dataPtr)
static LogicalResult replaceTransferOpWithMasked (ConversionPatternRewriter &rewriter, LLVMTypeConverter &typeConverter, Location loc, TransferWriteOp xferOp, ArrayRef< Value > operands, Value dataPtr, Value mask)
static TransferReadOpAdaptor getTransferOpAdapter (TransferReadOp xferOp, ArrayRef< Value > operands)
static TransferWriteOpAdaptor getTransferOpAdapter (TransferWriteOp xferOp, ArrayRef< Value > operands)
Function Documentation
buildVectorComparison()
static Value buildVectorComparison (ConversionPatternRewriter & rewriter, Operation * op, bool enableIndexOptimizations, int64_t dim, Value b, Value * off = nullptr) static
Definition at line 123 of file ConvertVectorToLLVM.cpp.
References mlir::PatternRewriter::create(), mlir::Builder::getI32Type(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getI64Type(), mlir::Builder::getI64VectorAttr(), mlir::Operation::getLoc(), mlir::Value::getType(), and mlir::edsc::op::slt().
Referenced by getTransferOpAdapter().
extractOne() [1/2]
static Value extractOne (ConversionPatternRewriter & rewriter, LLVMTypeConverter & typeConverter, Location loc, Value val, Type llvmType, int64_t rank, int64_t pos) static
Definition at line 75 of file ConvertVectorToLLVM.cpp.
References mlir::TypeConverter::convertType(), mlir::PatternRewriter::create(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexType(), and mlir::Builder::getIntegerAttr().
Referenced by getTransferOpAdapter().
extractOne() [2/2]
static Value extractOne (PatternRewriter & rewriter, Location loc, Value vector, int64_t offset) static
Definition at line 91 of file ConvertVectorToLLVM.cpp.
References mlir::Type::cast(), mlir::PatternRewriter::create(), and mlir::Value::getType().
getBase()
static LogicalResult getBase (ConversionPatternRewriter & rewriter, Location loc, Value memref, MemRefType memRefType, Value & base) static
Definition at line 174 of file ConvertVectorToLLVM.cpp.
References mlir::MemRefDescriptor::alignedPtr(), mlir::failed(), mlir::failure(), mlir::getStridesAndOffset(), and mlir::success().
Referenced by getBasePtr(), getIndexedPtrs(), mlir::ResultRange::getTypes(), mlir::edsc::TemplatedIndexedValue< Load, Store >::operator%=(), mlir::edsc::TemplatedIndexedValue< Load, Store >::operator*=(), mlir::edsc::TemplatedIndexedValue< Load, Store >::operator+=(), mlir::edsc::TemplatedIndexedValue< Load, Store >::operator-=(), mlir::edsc::TemplatedIndexedValue< Load, Store >::operator/=(), and mlir::edsc::TemplatedIndexedValue< Load, Store >::operator^=().
getBasePtr() [1/2]
static LogicalResult getBasePtr (ConversionPatternRewriter & rewriter, Location loc, Value memref, MemRefType memRefType, Value & ptr) static
Definition at line 191 of file ConvertVectorToLLVM.cpp.
References mlir::PatternRewriter::create(), mlir::failed(), mlir::failure(), getBase(), mlir::MemRefDescriptor::getElementPtrType(), and mlir::success().
Referenced by getTransferOpAdapter().
getBasePtr() [2/2]
static LogicalResult getBasePtr (ConversionPatternRewriter & rewriter, Location loc, Value memref, MemRefType memRefType, Type type, Value & ptr) static
Definition at line 203 of file ConvertVectorToLLVM.cpp.
References mlir::PatternRewriter::create(), mlir::failed(), mlir::failure(), getBase(), and mlir::success().
getI64SubArray()
static SmallVector<int64_t, 4> getI64SubArray (ArrayAttr arrayAttr, unsigned dropFront = 0, unsigned dropBack = 0) static
Definition at line 103 of file ConvertVectorToLLVM.cpp.
References dropFront(), mlir::ArrayAttr::getAsRange(), and mlir::ArrayAttr::size().
Referenced by getTransferOpAdapter().
getIndexedPtrs()
static LogicalResult getIndexedPtrs (ConversionPatternRewriter & rewriter, Location loc, Value memref, Value indices, MemRefType memRefType, VectorType vType, Type iType, Value & ptrs) static
Definition at line 217 of file ConvertVectorToLLVM.cpp.
References mlir::PatternRewriter::create(), mlir::failed(), mlir::failure(), getBase(), mlir::MemRefDescriptor::getElementPtrType(), mlir::LLVM::LLVMType::getVectorTy(), and mlir::success().
Referenced by getTransferOpAdapter().
getMemRefAlignment()
template<typename T > LogicalResult getMemRefAlignment (LLVMTypeConverter & typeConverter, T op, unsigned & align)
Definition at line 157 of file ConvertVectorToLLVM.cpp.
References mlir::Type::cast(), mlir::TypeConverter::convertType(), mlir::failure(), mlir::LLVMTypeConverter::getDataLayout(), mlir::LLVM::TypeToLLVMIRTranslator::getPreferredAlignment(), and mlir::success().
Referenced by getTransferOpAdapter(), replaceTransferOpWithLoadOrStore(), and replaceTransferOpWithMasked().
getTransferOpAdapter() [1/2]
static TransferReadOpAdaptor getTransferOpAdapter (TransferReadOp xferOp, ArrayRef< Value > operands) static
Definition at line 296 of file ConvertVectorToLLVM.cpp.
Referenced by getTransferOpAdapter().
getTransferOpAdapter() [2/2]
static TransferWriteOpAdaptor getTransferOpAdapter (TransferWriteOp xferOp, ArrayRef< Value > operands) static
Definition at line 301 of file ConvertVectorToLLVM.cpp.
References mlir::MemRefDescriptor::alignedPtr(), mlir::MemRefDescriptor::allocatedPtr(), buildVectorComparison(), mlir::Value::cast(), mlir::Type::cast(), mlir::TypeConverter::convertType(), mlir::PatternRewriter::create(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::ConversionPatternRewriter::eraseOp(), extractOne(), mlir::failed(), mlir::failure(), mlir::ArrayAttr::get(), mlir::MemRefType::getAffineMaps(), getBasePtr(), mlir::Builder::getBoolAttr(), mlir::Builder::getContext(), mlir::Operation::getContext(), mlir::LLVM::LLVMType::getDoubleTy(), mlir::Builder::getFloatAttr(), mlir::LLVM::LLVMType::getFloatTy(), mlir::LLVM::LLVMType::getFunctionTy(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI64ArrayAttr(), getI64SubArray(), getIndexedPtrs(), mlir::Builder::getIndexType(), mlir::LLVM::LLVMType::getInt64Ty(), mlir::Builder::getIntegerAttr(), mlir::Operation::getLoc(), getMemRefAlignment(), mlir::AffineMap::getMinorIdentityMap(), mlir::Operation::getParentOfType(), mlir::Operation::getResult(), mlir::MemRefType::getShape(), mlir::getStridesAndOffset(), mlir::Builder::getSymbolRefAttr(), getTransferOpAdapter(), mlir::Value::getType(), mlir::LLVM::LLVMType::getVoidTy(), mlir::Builder::getZeroAttr(), insertOne(), mlir::Type::isa(), mlir::ShapedType::isDynamic(), mlir::ShapedType::isDynamicStrideOrOffset(), mlir::Type::isIndex(), mlir::Type::isIntOrIndex(), mlir::Type::isUnsignedInteger(), mlir::vector::None, printComma(), mlir::LLVM::detail::printType(), reducedVectorTypeBack(), reducedVectorTypeFront(), mlir::PatternRewriter::replaceOp(), mlir::ConversionPatternRewriter::replaceOp(), mlir::PatternRewriter::replaceOpWithNewOp(), replaceTransferOpWithLoadOrStore(), replaceTransferOpWithMasked(), mlir::success(), and mlir::MemRefDescriptor::undef().
insertOne() [1/2]
static Value insertOne (ConversionPatternRewriter & rewriter, LLVMTypeConverter & typeConverter, Location loc, Value val1, Value val2, Type llvmType, int64_t rank, int64_t pos) static
Definition at line 47 of file ConvertVectorToLLVM.cpp.
References mlir::TypeConverter::convertType(), mlir::PatternRewriter::create(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexType(), and mlir::Builder::getIntegerAttr().
Referenced by getTransferOpAdapter().
insertOne() [2/2]
static Value insertOne (PatternRewriter & rewriter, Location loc, Value from, Value into, int64_t offset) static
Definition at line 64 of file ConvertVectorToLLVM.cpp.
References mlir::Type::cast(), mlir::PatternRewriter::create(), and mlir::Value::getType().
reducedVectorTypeBack()
static VectorType reducedVectorTypeBack (VectorType tp) static
Definition at line 41 of file ConvertVectorToLLVM.cpp.
References mlir::VectorType::get(), and mlir::VectorType::getShape().
Referenced by getTransferOpAdapter().
reducedVectorTypeFront()
static VectorType reducedVectorTypeFront (VectorType tp) static
Definition at line 35 of file ConvertVectorToLLVM.cpp.
References mlir::VectorType::get(), and mlir::VectorType::getShape().
Referenced by getTransferOpAdapter().
replaceTransferOpWithLoadOrStore() [1/2]
static LogicalResult replaceTransferOpWithLoadOrStore (ConversionPatternRewriter & rewriter, LLVMTypeConverter & typeConverter, Location loc, TransferReadOp xferOp, ArrayRef< Value > operands, Value dataPtr) static
Definition at line 231 of file ConvertVectorToLLVM.cpp.
References mlir::failed(), mlir::failure(), getMemRefAlignment(), mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
Referenced by getTransferOpAdapter().
replaceTransferOpWithLoadOrStore() [2/2]
static LogicalResult replaceTransferOpWithLoadOrStore (ConversionPatternRewriter & rewriter, LLVMTypeConverter & typeConverter, Location loc, TransferWriteOp xferOp, ArrayRef< Value > operands, Value dataPtr) static
Definition at line 267 of file ConvertVectorToLLVM.cpp.
References mlir::failed(), mlir::failure(), getMemRefAlignment(), mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
replaceTransferOpWithMasked() [1/2]
static LogicalResult replaceTransferOpWithMasked (ConversionPatternRewriter & rewriter, LLVMTypeConverter & typeConverter, Location loc, TransferReadOp xferOp, ArrayRef< Value > operands, Value dataPtr, Value mask) static
Definition at line 243 of file ConvertVectorToLLVM.cpp.
References mlir::TypeConverter::convertType(), mlir::PatternRewriter::create(), mlir::failed(), mlir::failure(), mlir::Builder::getI32IntegerAttr(), getMemRefAlignment(), mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
Referenced by getTransferOpAdapter().
replaceTransferOpWithMasked() [2/2]
static LogicalResult replaceTransferOpWithMasked (ConversionPatternRewriter & rewriter, LLVMTypeConverter & typeConverter, Location loc, TransferWriteOp xferOp, ArrayRef< Value > operands, Value dataPtr, Value mask) static
Definition at line 281 of file ConvertVectorToLLVM.cpp.
References mlir::failed(), mlir::failure(), mlir::Builder::getI32IntegerAttr(), getMemRefAlignment(), mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().