MLIR: lib/CAPI/IR/IR.cpp File Reference
IR.cpp File Reference
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Support.h"
#include "mlir/CAPI/Utils.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/Types.h"
#include "mlir/Parser.h"
Macros
#define APPEND_ELEMS(type, sizeName, elemName)
Functions
MlirContext mlirContextCreate ()
Creates an MLIR context and transfers its ownership to the caller.
int mlirContextEqual (MlirContext ctx1, MlirContext ctx2)
Checks if two contexts are equal.
void mlirContextDestroy (MlirContext context)
Takes an MLIR context owned by the caller and destroys it.
void mlirContextSetAllowUnregisteredDialects (MlirContext context, int allow)
Sets whether unregistered dialects are allowed in this context.
int mlirContextGetAllowUnregisteredDialects (MlirContext context)
Returns whether the context allows unregistered dialects.
intptr_t mlirContextGetNumRegisteredDialects (MlirContext context)
Returns the number of dialects registered with the given context.
intptr_t mlirContextGetNumLoadedDialects (MlirContext context)
Returns the number of dialects loaded by the context.
MlirDialect mlirContextGetOrLoadDialect (MlirContext context, MlirStringRef name)
Gets the dialect instance owned by the given context using the dialect namespace to identify it, loads (i.e., constructs the instance of) the dialect if necessary.
MlirContext mlirDialectGetContext (MlirDialect dialect)
Returns the context that owns the dialect.
int mlirDialectEqual (MlirDialect dialect1, MlirDialect dialect2)
Checks if two dialects that belong to the same context are equal.
MlirStringRef mlirDialectGetNamespace (MlirDialect dialect)
Returns the namespace of the given dialect.
MlirOpPrintingFlags mlirOpPrintingFlagsCreate ()
Creates new printing flags with defaults, intended for customization.
void mlirOpPrintingFlagsDestroy (MlirOpPrintingFlags flags)
Destroys printing flags created with mlirOpPrintingFlagsCreate.
void mlirOpPrintingFlagsElideLargeElementsAttrs (MlirOpPrintingFlags flags, intptr_t largeElementLimit)
Enables the elision of large elements attributes by printing a lexically valid but otherwise meaningless form instead of the element data.
void mlirOpPrintingFlagsEnableDebugInfo (MlirOpPrintingFlags flags, int prettyForm)
Enable printing of debug information.
void mlirOpPrintingFlagsPrintGenericOpForm (MlirOpPrintingFlags flags)
Always print operations in the generic form.
void mlirOpPrintingFlagsUseLocalScope (MlirOpPrintingFlags flags)
Use local scope when printing the operation.
MlirLocation mlirLocationFileLineColGet (MlirContext context, const char *filename, unsigned line, unsigned col)
Creates an File/Line/Column location owned by the given context.
MlirLocation mlirLocationUnknownGet (MlirContext context)
Creates a location with unknown position owned by the given context.
MlirContext mlirLocationGetContext (MlirLocation location)
Gets the context that a location was created with.
void mlirLocationPrint (MlirLocation location, MlirStringCallback callback, void *userData)
Prints a location by sending chunks of the string representation and forwarding userData tocallback`.
MlirModule mlirModuleCreateEmpty (MlirLocation location)
Creates a new, empty module and transfers ownership to the caller.
MlirModule mlirModuleCreateParse (MlirContext context, const char *module)
Parses a module from the string and transfers ownership to the caller.
MlirContext mlirModuleGetContext (MlirModule module)
Gets the context that a module was created with.
void mlirModuleDestroy (MlirModule module)
Takes a module owned by the caller and deletes it.
MlirOperation mlirModuleGetOperation (MlirModule module)
Views the module as a generic operation.
MlirOperationState mlirOperationStateGet (const char *name, MlirLocation loc)
Constructs an operation state from a name and a location.
void mlirOperationStateAddResults (MlirOperationState *state, intptr_t n, MlirType *results)
Adds a list of components to the operation state.
void mlirOperationStateAddOperands (MlirOperationState *state, intptr_t n, MlirValue *operands)
void mlirOperationStateAddOwnedRegions (MlirOperationState *state, intptr_t n, MlirRegion *regions)
void mlirOperationStateAddSuccessors (MlirOperationState *state, intptr_t n, MlirBlock *successors)
void mlirOperationStateAddAttributes (MlirOperationState *state, intptr_t n, MlirNamedAttribute *attributes)
MlirOperation mlirOperationCreate (const MlirOperationState *state)
Creates an operation and transfers ownership to the caller.
void mlirOperationDestroy (MlirOperation op)
Takes an operation owned by the caller and destroys it.
int mlirOperationEqual (MlirOperation op, MlirOperation other)
Checks whether two operation handles point to the same operation.
intptr_t mlirOperationGetNumRegions (MlirOperation op)
Returns the number of regions attached to the given operation.
MlirRegion mlirOperationGetRegion (MlirOperation op, intptr_t pos)
Returns pos-th region attached to the operation.
MlirOperation mlirOperationGetNextInBlock (MlirOperation op)
Returns an operation immediately following the given operation it its enclosing block.
intptr_t mlirOperationGetNumOperands (MlirOperation op)
Returns the number of operands of the operation.
MlirValue mlirOperationGetOperand (MlirOperation op, intptr_t pos)
Returns pos-th operand of the operation.
intptr_t mlirOperationGetNumResults (MlirOperation op)
Returns the number of results of the operation.
MlirValue mlirOperationGetResult (MlirOperation op, intptr_t pos)
Returns pos-th result of the operation.
intptr_t mlirOperationGetNumSuccessors (MlirOperation op)
Returns the number of successor blocks of the operation.
MlirBlock mlirOperationGetSuccessor (MlirOperation op, intptr_t pos)
Returns pos-th successor of the operation.
intptr_t mlirOperationGetNumAttributes (MlirOperation op)
Returns the number of attributes attached to the operation.
MlirNamedAttribute mlirOperationGetAttribute (MlirOperation op, intptr_t pos)
Return pos-th attribute of the operation.
MlirAttribute mlirOperationGetAttributeByName (MlirOperation op, const char *name)
Returns an attribute attached to the operation given its name.
void mlirOperationSetAttributeByName (MlirOperation op, const char *name, MlirAttribute attr)
Sets an attribute by name, replacing the existing if it exists or adding a new one otherwise.
int mlirOperationRemoveAttributeByName (MlirOperation op, const char *name)
Removes an attribute by name.
void mlirOperationPrint (MlirOperation op, MlirStringCallback callback, void *userData)
Prints an operation by sending chunks of the string representation and forwarding userData tocallback`.
void mlirOperationPrintWithFlags (MlirOperation op, MlirOpPrintingFlags flags, MlirStringCallback callback, void *userData)
Same as mlirOperationPrint but accepts flags controlling the printing behavior.
void mlirOperationDump (MlirOperation op)
Prints an operation to stderr.
MlirRegion mlirRegionCreate ()
Creates a new empty region and transfers ownership to the caller.
MlirBlock mlirRegionGetFirstBlock (MlirRegion region)
Gets the first block in the region.
void mlirRegionAppendOwnedBlock (MlirRegion region, MlirBlock block)
Takes a block owned by the caller and appends it to the given region.
void mlirRegionInsertOwnedBlock (MlirRegion region, intptr_t pos, MlirBlock block)
Takes a block owned by the caller and inserts it at pos to the given region.
void mlirRegionInsertOwnedBlockAfter (MlirRegion region, MlirBlock reference, MlirBlock block)
Takes a block owned by the caller and inserts it after the (non-owned) reference block in the given region.
void mlirRegionInsertOwnedBlockBefore (MlirRegion region, MlirBlock reference, MlirBlock block)
Takes a block owned by the caller and inserts it before the (non-owned) reference block in the given region.
void mlirRegionDestroy (MlirRegion region)
Takes a region owned by the caller and destroys it.
MlirBlock mlirBlockCreate (intptr_t nArgs, MlirType *args)
Creates a new empty block with the given argument types and transfers ownership to the caller.
int mlirBlockEqual (MlirBlock block, MlirBlock other)
Checks whether two blocks handles point to the same block.
MlirBlock mlirBlockGetNextInRegion (MlirBlock block)
Returns the block immediately following the given block in its parent region.
MlirOperation mlirBlockGetFirstOperation (MlirBlock block)
Returns the first operation in the block.
void mlirBlockAppendOwnedOperation (MlirBlock block, MlirOperation operation)
Takes an operation owned by the caller and appends it to the block.
void mlirBlockInsertOwnedOperation (MlirBlock block, intptr_t pos, MlirOperation operation)
Takes an operation owned by the caller and inserts it as pos to the block.
void mlirBlockInsertOwnedOperationAfter (MlirBlock block, MlirOperation reference, MlirOperation operation)
Takes an operation owned by the caller and inserts it after the (non-owned) reference operation in the given block.
void mlirBlockInsertOwnedOperationBefore (MlirBlock block, MlirOperation reference, MlirOperation operation)
Takes an operation owned by the caller and inserts it before the (non-owned) reference operation in the given block.
void mlirBlockDestroy (MlirBlock block)
Takes a block owned by the caller and destroys it.
intptr_t mlirBlockGetNumArguments (MlirBlock block)
Returns the number of arguments of the block.
MlirValue mlirBlockGetArgument (MlirBlock block, intptr_t pos)
Returns pos-th argument of the block.
void mlirBlockPrint (MlirBlock block, MlirStringCallback callback, void *userData)
Prints a block by sending chunks of the string representation and forwarding userData tocallback`.
int mlirValueIsABlockArgument (MlirValue value)
Returns 1 if the value is a block argument, 0 otherwise.
int mlirValueIsAOpResult (MlirValue value)
Returns 1 if the value is an operation result, 0 otherwise.
MlirBlock mlirBlockArgumentGetOwner (MlirValue value)
Returns the block in which this value is defined as an argument.
intptr_t mlirBlockArgumentGetArgNumber (MlirValue value)
Returns the position of the value in the argument list of its block.
void mlirBlockArgumentSetType (MlirValue value, MlirType type)
Sets the type of the block argument to the given type.
MlirOperation mlirOpResultGetOwner (MlirValue value)
Returns an operation that produced this value as its result.
intptr_t mlirOpResultGetResultNumber (MlirValue value)
Returns the position of the value in the list of results of the operation that produced it.
MlirType mlirValueGetType (MlirValue value)
Returns the type of the value.
void mlirValueDump (MlirValue value)
Prints the value to the standard error stream.
void mlirValuePrint (MlirValue value, MlirStringCallback callback, void *userData)
Prints a value by sending chunks of the string representation and forwarding userData tocallback`.
MlirType mlirTypeParseGet (MlirContext context, const char *type)
Parses a type.
MlirContext mlirTypeGetContext (MlirType type)
Gets the context that a type was created with.
int mlirTypeEqual (MlirType t1, MlirType t2)
Checks if two types are equal.
void mlirTypePrint (MlirType type, MlirStringCallback callback, void *userData)
Prints a location by sending chunks of the string representation and forwarding userData tocallback`.
void mlirTypeDump (MlirType type)
Prints the type to the standard error stream.
MlirAttribute mlirAttributeParseGet (MlirContext context, const char *attr)
Parses an attribute.
MlirContext mlirAttributeGetContext (MlirAttribute attribute)
Gets the context that an attribute was created with.
MlirType mlirAttributeGetType (MlirAttribute attribute)
Gets the type of this attribute.
int mlirAttributeEqual (MlirAttribute a1, MlirAttribute a2)
Checks if two attributes are equal.
void mlirAttributePrint (MlirAttribute attr, MlirStringCallback callback, void *userData)
Prints an attribute by sending chunks of the string representation and forwarding userData tocallback`.
void mlirAttributeDump (MlirAttribute attr)
Prints the attribute to the standard error stream.
MlirNamedAttribute mlirNamedAttributeGet (const char *name, MlirAttribute attr)
Associates an attribute with the name.
Macro Definition Documentation
APPEND_ELEMS
#define APPEND_ELEMS (type, sizeName, elemName)
Value:
state->elemName =                                                            \
      (type *)realloc(state->elemName, (state->sizeName + n) * sizeof(type));  \
  memcpy(state->elemName + state->sizeName, elemName, n * sizeof(type));       \
  state->sizeName += n;
Definition at line 181 of file IR.cpp.
Referenced by mlirOperationStateAddAttributes(), mlirOperationStateAddOperands(), mlirOperationStateAddOwnedRegions(), mlirOperationStateAddResults(), and mlirOperationStateAddSuccessors().
Function Documentation
mlirAttributeDump()
void mlirAttributeDump (MlirAttribute attr)
Prints the attribute to the standard error stream.
Definition at line 552 of file IR.cpp.
References unwrap().
Referenced by mlirAttributeIsNull(), and mlir::python::PyType::operator==().
mlirAttributeEqual()
int mlirAttributeEqual (MlirAttribute a1, MlirAttribute a2)
Checks if two attributes are equal.
Definition at line 541 of file IR.cpp.
References unwrap().
Referenced by mlirAttributeIsNull(), and mlir::python::PyAttribute::operator==().
mlirAttributeGetContext()
MlirContext mlirAttributeGetContext (MlirAttribute attribute)
Gets the context that an attribute was created with.
Definition at line 533 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirTypeIsNull(), and mlir::python::PyType::operator==().
mlirAttributeGetType()
MlirType mlirAttributeGetType (MlirAttribute attribute)
Gets the type of this attribute.
Definition at line 537 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirTypeIsNull(), and mlir::python::PyType::operator==().
mlirAttributeParseGet()
MlirAttribute mlirAttributeParseGet (MlirContext context, const char * attr)
Parses an attribute.
The attribute is owned by the context.
Definition at line 529 of file IR.cpp.
References mlir::parseAttribute(), unwrap(), and wrap().
Referenced by mlirTypeIsNull(), and mlir::python::PyType::operator==().
mlirAttributePrint()
void mlirAttributePrint (MlirAttribute attr, MlirStringCallback callback, void * userData)
Prints an attribute by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 545 of file IR.cpp.
References mlir::Diagnostic::print(), and unwrap().
Referenced by mlirAttributeIsNull(), and mlir::python::PyType::operator==().
mlirBlockAppendOwnedOperation()
void mlirBlockAppendOwnedOperation (MlirBlock block, MlirOperation operation)
Takes an operation owned by the caller and appends it to the block.
Definition at line 402 of file IR.cpp.
References unwrap().
Referenced by mlirBlockInsertOwnedOperationBefore(), and mlirBlockIsNull().
mlirBlockArgumentGetArgNumber()
intptr_t mlirBlockArgumentGetArgNumber (MlirValue value)
Returns the position of the value in the argument list of its block.
Definition at line 472 of file IR.cpp.
References unwrap().
Referenced by mlirValueIsNull(), and mlir::python::PyType::operator==().
mlirBlockArgumentGetOwner()
MlirBlock mlirBlockArgumentGetOwner (MlirValue value)
Returns the block in which this value is defined as an argument.
Asserts if the value is not a block argument.
Definition at line 468 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirValueIsNull(), and mlir::python::PyType::operator==().
mlirBlockArgumentSetType()
void mlirBlockArgumentSetType (MlirValue value, MlirType type)
Sets the type of the block argument to the given type.
Definition at line 477 of file IR.cpp.
References unwrap().
Referenced by mlirValueIsNull(), and mlir::python::PyType::operator==().
mlirBlockCreate()
MlirBlock mlirBlockCreate (intptr_t nArgs, MlirType * args)
Creates a new empty block with the given argument types and transfers ownership to the caller.
Definition at line 380 of file IR.cpp.
References mlir::Block::addArgument(), unwrap(), and wrap().
Referenced by mlirRegionIsNull().
mlirBlockDestroy()
void mlirBlockDestroy (MlirBlock block)
Takes a block owned by the caller and destroys it.
Definition at line 439 of file IR.cpp.
References unwrap().
Referenced by mlirRegionIsNull().
mlirBlockEqual()
int mlirBlockEqual (MlirBlock block, MlirBlock other)
Checks whether two blocks handles point to the same block.
This does not perform deep comparison.
Definition at line 387 of file IR.cpp.
References unwrap().
Referenced by mlirBlockIsNull().
mlirBlockGetArgument()
MlirValue mlirBlockGetArgument (MlirBlock block, intptr_t pos)
Returns pos-th argument of the block.
Definition at line 445 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirBlockIsNull(), and mlir::python::PyType::operator==().
mlirBlockGetFirstOperation()
MlirOperation mlirBlockGetFirstOperation (MlirBlock block)
Returns the first operation in the block.
Definition at line 395 of file IR.cpp.
References mlir::Block::empty(), mlir::Block::front(), unwrap(), and wrap().
Referenced by mlirBlockIsNull(), and mlir::python::PyType::operator==().
mlirBlockGetNextInRegion()
MlirBlock mlirBlockGetNextInRegion (MlirBlock block)
Returns the block immediately following the given block in its parent region.
Definition at line 391 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirBlockIsNull().
mlirBlockGetNumArguments()
intptr_t mlirBlockGetNumArguments (MlirBlock block)
Returns the number of arguments of the block.
Definition at line 441 of file IR.cpp.
References unwrap().
Referenced by mlirBlockIsNull(), and mlir::python::PyType::operator==().
mlirBlockInsertOwnedOperation()
void mlirBlockInsertOwnedOperation (MlirBlock block, intptr_t pos, MlirOperation operation)
Takes an operation owned by the caller and inserts it as pos to the block.
This is an expensive operation that scans the block linearly, prefer insertBefore/After instead.
Definition at line 406 of file IR.cpp.
References unwrap().
Referenced by mlirBlockIsNull().
mlirBlockInsertOwnedOperationAfter()
void mlirBlockInsertOwnedOperationAfter (MlirBlock block, MlirOperation reference, MlirOperation operation)
Takes an operation owned by the caller and inserts it after the (non-owned) reference operation in the given block.
If the reference is null, prepends the operation. Otherwise, the reference must belong to the block.
Definition at line 412 of file IR.cpp.
References mlir::Block::begin(), mlir::Block::getOperations(), mlirOperationIsNull(), and unwrap().
Referenced by mlirBlockIsNull().
mlirBlockInsertOwnedOperationBefore()
void mlirBlockInsertOwnedOperationBefore (MlirBlock block, MlirOperation reference, MlirOperation operation)
Takes an operation owned by the caller and inserts it before the (non-owned) reference operation in the given block.
If the reference is null, appends the operation. Otherwise, the reference must belong to the block.
Definition at line 427 of file IR.cpp.
References mlirBlockAppendOwnedOperation(), mlirOperationIsNull(), and unwrap().
Referenced by mlirBlockIsNull().
mlirBlockPrint()
void mlirBlockPrint (MlirBlock block, MlirStringCallback callback, void * userData)
Prints a block by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 449 of file IR.cpp.
References mlir::Diagnostic::print(), and unwrap().
Referenced by mlirBlockIsNull(), and mlir::python::PyType::operator==().
mlirContextCreate()
MlirContext mlirContextCreate ()
Creates an MLIR context and transfers its ownership to the caller.
Definition at line 28 of file IR.cpp.
References wrap().
Referenced by mlir::python::PyMlirContext::createNewContextForInit().
mlirContextDestroy()
void mlirContextDestroy (MlirContext context)
Takes an MLIR context owned by the caller and destroys it.
Definition at line 37 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull(), and mlir::python::PyMlirContext::~PyMlirContext().
mlirContextEqual()
int mlirContextEqual (MlirContext ctx1, MlirContext ctx2)
Checks if two contexts are equal.
Definition at line 33 of file IR.cpp.
References unwrap().
mlirContextGetAllowUnregisteredDialects()
int mlirContextGetAllowUnregisteredDialects (MlirContext context)
Returns whether the context allows unregistered dialects.
Definition at line 43 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull(), and mlir::python::PyType::operator==().
mlirContextGetNumLoadedDialects()
intptr_t mlirContextGetNumLoadedDialects (MlirContext context)
Returns the number of dialects loaded by the context.
Definition at line 52 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull().
mlirContextGetNumRegisteredDialects()
intptr_t mlirContextGetNumRegisteredDialects (MlirContext context)
Returns the number of dialects registered with the given context.
A registered dialect will be loaded if needed by the parser.
Definition at line 46 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull().
mlirContextGetOrLoadDialect()
MlirDialect mlirContextGetOrLoadDialect (MlirContext context, MlirStringRef name)
Gets the dialect instance owned by the given context using the dialect namespace to identify it, loads (i.e., constructs the instance of) the dialect if necessary.
If the dialect is not registered with the context, returns null. Use mlirContextLoad<Name>Dialect to load an unregistered dialect.
Definition at line 56 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirContextIsNull().
mlirContextSetAllowUnregisteredDialects()
void mlirContextSetAllowUnregisteredDialects (MlirContext context, int allow)
Sets whether unregistered dialects are allowed in this context.
Definition at line 39 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull(), and mlir::python::PyType::operator==().
mlirDialectEqual()
int mlirDialectEqual (MlirDialect dialect1, MlirDialect dialect2)
Checks if two dialects that belong to the same context are equal.
Dialects from different contexts will not compare equal.
Definition at line 69 of file IR.cpp.
References unwrap().
Referenced by mlirDialectIsNull().
mlirDialectGetContext()
MlirContext mlirDialectGetContext (MlirDialect dialect)
Returns the context that owns the dialect.
Definition at line 65 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirContextIsNull().
mlirDialectGetNamespace()
MlirStringRef mlirDialectGetNamespace (MlirDialect dialect)
Returns the namespace of the given dialect.
Definition at line 73 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirDialectIsNull().
mlirLocationFileLineColGet()
MlirLocation mlirLocationFileLineColGet (MlirContext context, const char * filename, unsigned line, unsigned col)
Creates an File/Line/Column location owned by the given context.
Definition at line 111 of file IR.cpp.
References mlir::FileLineColLoc::get(), unwrap(), and wrap().
Referenced by mlirDialectIsNull(), and mlir::python::PyType::operator==().
mlirLocationGetContext()
MlirContext mlirLocationGetContext (MlirLocation location)
Gets the context that a location was created with.
Definition at line 121 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirDialectIsNull().
mlirLocationPrint()
void mlirLocationPrint (MlirLocation location, MlirStringCallback callback, void * userData)
Prints a location by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 125 of file IR.cpp.
References mlir::Diagnostic::print(), and unwrap().
Referenced by mlirDialectIsNull(), and mlir::python::PyType::operator==().
mlirLocationUnknownGet()
MlirLocation mlirLocationUnknownGet (MlirContext context)
Creates a location with unknown position owned by the given context.
Definition at line 117 of file IR.cpp.
References mlir::UnknownLoc::get(), unwrap(), and wrap().
Referenced by mlirDialectIsNull(), and mlir::python::PyType::operator==().
mlirModuleCreateEmpty()
MlirModule mlirModuleCreateEmpty (MlirLocation location)
Creates a new, empty module and transfers ownership to the caller.
Definition at line 136 of file IR.cpp.
References mlir::ModuleOp::create(), unwrap(), and wrap().
Referenced by mlirDialectIsNull(), and mlir::python::PyType::operator==().
mlirModuleCreateParse()
MlirModule mlirModuleCreateParse (MlirContext context, const char * module)
Parses a module from the string and transfers ownership to the caller.
Definition at line 140 of file IR.cpp.
References mlir::Op< ConcreteType, Traits >::getOperation(), mlir::parseSourceString(), mlir::OwningOpRefBase< OpTy >::release(), and unwrap().
Referenced by mlirDialectIsNull(), and mlir::python::PyType::operator==().
mlirModuleDestroy()
void mlirModuleDestroy (MlirModule module)
Takes a module owned by the caller and deletes it.
Definition at line 151 of file IR.cpp.
References unwrap().
Referenced by mlirModuleIsNull(), and mlir::python::PyModule::~PyModule().
mlirModuleGetContext()
MlirContext mlirModuleGetContext (MlirModule module)
Gets the context that a module was created with.
Definition at line 147 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyModule::forModule(), and mlirDialectIsNull().
mlirModuleGetOperation()
MlirOperation mlirModuleGetOperation (MlirModule module)
Views the module as a generic operation.
Definition at line 156 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirModuleIsNull(), and mlir::python::PyType::operator==().
mlirNamedAttributeGet()
MlirNamedAttribute mlirNamedAttributeGet (const char * name, MlirAttribute attr)
Associates an attribute with the name.
Takes ownership of neither.
Definition at line 554 of file IR.cpp.
Referenced by mlir::python::PyMlirContext::createOperation(), mlirAttributeIsNull(), and mlir::python::PyNamedAttribute::PyNamedAttribute().
mlirOperationCreate()
MlirOperation mlirOperationCreate (const MlirOperationState * state)
Creates an operation and transfers ownership to the caller.
Definition at line 213 of file IR.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addSuccessors(), mlir::OperationState::addTypes(), MlirNamedAttribute::attribute, MlirOperationState::attributes, mlir::OperationState::attributes, mlir::Operation::create(), MlirOperationState::location, MlirNamedAttribute::name, MlirOperationState::name, MlirOperationState::nAttributes, MlirOperationState::nOperands, MlirOperationState::nRegions, MlirOperationState::nResults, MlirOperationState::nSuccessors, MlirOperationState::operands, MlirOperationState::regions, mlir::NamedAttrList::reserve(), MlirOperationState::results, MlirOperationState::successors, unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::PyMlirContext::createOperation().
mlirOperationDestroy()
void mlirOperationDestroy (MlirOperation op)
Takes an operation owned by the caller and destroys it.
Definition at line 242 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyOperation::~PyOperation().
mlirOperationDump()
void mlirOperationDump (MlirOperation op)
Prints an operation to stderr.
Definition at line 322 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull(), and mlir::python::PyType::operator==().
mlirOperationEqual()
int mlirOperationEqual (MlirOperation op, MlirOperation other)
Checks whether two operation handles point to the same operation.
This does not perform deep comparison.
Definition at line 244 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull(), and mlir::python::PyType::operator==().
mlirOperationGetAttribute()
MlirNamedAttribute mlirOperationGetAttribute (MlirOperation op, intptr_t pos)
Return pos-th attribute of the operation.
Definition at line 288 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirOperationIsNull().
mlirOperationGetAttributeByName()
MlirAttribute mlirOperationGetAttributeByName (MlirOperation op, const char * name)
Returns an attribute attached to the operation given its name.
Definition at line 293 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirOperationIsNull().
mlirOperationGetNextInBlock()
MlirOperation mlirOperationGetNextInBlock (MlirOperation op)
Returns an operation immediately following the given operation it its enclosing block.
Definition at line 256 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirOperationIsNull().
mlirOperationGetNumAttributes()
intptr_t mlirOperationGetNumAttributes (MlirOperation op)
Returns the number of attributes attached to the operation.
Definition at line 284 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull().
mlirOperationGetNumOperands()
intptr_t mlirOperationGetNumOperands (MlirOperation op)
Returns the number of operands of the operation.
Definition at line 260 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull().
mlirOperationGetNumRegions()
intptr_t mlirOperationGetNumRegions (MlirOperation op)
Returns the number of regions attached to the given operation.
Definition at line 248 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull().
mlirOperationGetNumResults()
intptr_t mlirOperationGetNumResults (MlirOperation op)
Returns the number of results of the operation.
Definition at line 268 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull(), and mlir::python::PyType::operator==().
mlirOperationGetNumSuccessors()
intptr_t mlirOperationGetNumSuccessors (MlirOperation op)
Returns the number of successor blocks of the operation.
Definition at line 276 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull().
mlirOperationGetOperand()
MlirValue mlirOperationGetOperand (MlirOperation op, intptr_t pos)
Returns pos-th operand of the operation.
Definition at line 264 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirOperationIsNull().
mlirOperationGetRegion()
MlirRegion mlirOperationGetRegion (MlirOperation op, intptr_t pos)
Returns pos-th region attached to the operation.
Definition at line 252 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirOperationIsNull().
mlirOperationGetResult()
MlirValue mlirOperationGetResult (MlirOperation op, intptr_t pos)
Returns pos-th result of the operation.
Definition at line 272 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirOperationIsNull(), and mlir::python::PyType::operator==().
mlirOperationGetSuccessor()
MlirBlock mlirOperationGetSuccessor (MlirOperation op, intptr_t pos)
Returns pos-th successor of the operation.
Definition at line 280 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirOperationIsNull().
mlirOperationPrint()
void mlirOperationPrint (MlirOperation op, MlirStringCallback callback, void * userData)
Prints an operation by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 308 of file IR.cpp.
References mlir::Diagnostic::print(), and unwrap().
Referenced by mlirOperationIsNull(), and mlir::python::PyType::operator==().
mlirOperationPrintWithFlags()
void mlirOperationPrintWithFlags (MlirOperation op, MlirOpPrintingFlags flags, MlirStringCallback callback, void * userData)
Same as mlirOperationPrint but accepts flags controlling the printing behavior.
Definition at line 315 of file IR.cpp.
References mlir::Diagnostic::print(), and unwrap().
Referenced by mlirOperationIsNull(), and mlir::python::PyOperation::print().
mlirOperationRemoveAttributeByName()
int mlirOperationRemoveAttributeByName (MlirOperation op, const char * name)
Removes an attribute by name.
Returns 0 if the attribute was not found and !0 if removed.
Definition at line 303 of file IR.cpp.
References mlir::MutableDictionaryAttr::Removed, and unwrap().
Referenced by mlirOperationIsNull().
mlirOperationSetAttributeByName()
void mlirOperationSetAttributeByName (MlirOperation op, const char * name, MlirAttribute attr)
Sets an attribute by name, replacing the existing if it exists or adding a new one otherwise.
Definition at line 298 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull().
mlirOperationStateAddAttributes()
void mlirOperationStateAddAttributes (MlirOperationState * state, intptr_t n, MlirNamedAttribute * attributes)
Definition at line 204 of file IR.cpp.
References APPEND_ELEMS.
Referenced by mlir::python::PyMlirContext::createOperation().
mlirOperationStateAddOperands()
void mlirOperationStateAddOperands (MlirOperationState * state, intptr_t n, MlirValue * operands)
Definition at line 192 of file IR.cpp.
References APPEND_ELEMS.
mlirOperationStateAddOwnedRegions()
void mlirOperationStateAddOwnedRegions (MlirOperationState * state, intptr_t n, MlirRegion * regions)
Definition at line 196 of file IR.cpp.
References APPEND_ELEMS.
Referenced by mlir::python::PyMlirContext::createOperation().
mlirOperationStateAddResults()
void mlirOperationStateAddResults (MlirOperationState * state, intptr_t n, MlirType * results)
Adds a list of components to the operation state.
Definition at line 187 of file IR.cpp.
References APPEND_ELEMS.
Referenced by mlir::python::PyMlirContext::createOperation().
mlirOperationStateAddSuccessors()
void mlirOperationStateAddSuccessors (MlirOperationState * state, intptr_t n, MlirBlock * successors)
Definition at line 200 of file IR.cpp.
References APPEND_ELEMS.
Referenced by mlir::python::PyMlirContext::createOperation().
mlirOperationStateGet()
MlirOperationState mlirOperationStateGet (const char * name, MlirLocation loc)
Constructs an operation state from a name and a location.
Definition at line 164 of file IR.cpp.
References MlirOperationState::attributes, MlirOperationState::location, MlirOperationState::name, MlirOperationState::nAttributes, MlirOperationState::nOperands, MlirOperationState::nRegions, MlirOperationState::nResults, MlirOperationState::nSuccessors, MlirOperationState::operands, MlirOperationState::regions, MlirOperationState::results, and MlirOperationState::successors.
Referenced by mlir::python::PyMlirContext::createOperation().
mlirOpPrintingFlagsCreate()
MlirOpPrintingFlags mlirOpPrintingFlagsCreate ()
Creates new printing flags with defaults, intended for customization.
Must be freed with a call to mlirOpPrintingFlagsDestroy().
Definition at line 81 of file IR.cpp.
References wrap().
Referenced by mlir::python::PyOperation::print().
mlirOpPrintingFlagsDestroy()
void mlirOpPrintingFlagsDestroy (MlirOpPrintingFlags flags)
Destroys printing flags created with mlirOpPrintingFlagsCreate.
Definition at line 85 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyOperation::print().
mlirOpPrintingFlagsElideLargeElementsAttrs()
void mlirOpPrintingFlagsElideLargeElementsAttrs (MlirOpPrintingFlags flags, intptr_t largeElementLimit)
Enables the elision of large elements attributes by printing a lexically valid but otherwise meaningless form instead of the element data.
The largeElementLimit is used to configure what is considered to be a "large" ElementsAttr by providing an upper limit to the number of elements.
Definition at line 89 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyOperation::print().
mlirOpPrintingFlagsEnableDebugInfo()
void mlirOpPrintingFlagsEnableDebugInfo (MlirOpPrintingFlags flags, int prettyForm)
Enable printing of debug information.
If 'prettyForm' is set to true, debug information is printed in a more readable 'pretty' form. Note: The IR generated with 'prettyForm' is not parsable.
Definition at line 94 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyOperation::print().
mlirOpPrintingFlagsPrintGenericOpForm()
void mlirOpPrintingFlagsPrintGenericOpForm (MlirOpPrintingFlags flags)
Always print operations in the generic form.
Definition at line 99 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyOperation::print().
mlirOpPrintingFlagsUseLocalScope()
void mlirOpPrintingFlagsUseLocalScope (MlirOpPrintingFlags flags)
Use local scope when printing the operation.
This allows for using the printer in a more localized and thread-safe setting, but may not necessarily be identical to what the IR will look like when dumping the full module.
Definition at line 103 of file IR.cpp.
References unwrap().
mlirOpResultGetOwner()
MlirOperation mlirOpResultGetOwner (MlirValue value)
Returns an operation that produced this value as its result.
Asserts if the value is not an op result.
Definition at line 481 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirValueIsNull(), and mlir::python::PyType::operator==().
mlirOpResultGetResultNumber()
intptr_t mlirOpResultGetResultNumber (MlirValue value)
Returns the position of the value in the list of results of the operation that produced it.
Definition at line 485 of file IR.cpp.
References unwrap().
Referenced by mlirValueIsNull(), and mlir::python::PyType::operator==().
mlirRegionAppendOwnedBlock()
void mlirRegionAppendOwnedBlock (MlirRegion region, MlirBlock block)
Takes a block owned by the caller and appends it to the given region.
Definition at line 337 of file IR.cpp.
References unwrap().
Referenced by mlirRegionInsertOwnedBlockBefore(), and mlirRegionIsNull().
mlirRegionCreate()
MlirRegion mlirRegionCreate ()
Creates a new empty region and transfers ownership to the caller.
Definition at line 328 of file IR.cpp.
References wrap().
Referenced by mlir::python::PyMlirContext::createOperation(), and mlirOperationIsNull().
mlirRegionDestroy()
void mlirRegionDestroy (MlirRegion region)
Takes a region owned by the caller and destroys it.
Definition at line 372 of file IR.cpp.
Referenced by mlirOperationIsNull().
mlirRegionGetFirstBlock()
MlirBlock mlirRegionGetFirstBlock (MlirRegion region)
Gets the first block in the region.
Definition at line 330 of file IR.cpp.
References mlir::Region::empty(), mlir::Region::front(), unwrap(), and wrap().
Referenced by mlirRegionIsNull(), and mlir::python::PyType::operator==().
mlirRegionInsertOwnedBlock()
void mlirRegionInsertOwnedBlock (MlirRegion region, intptr_t pos, MlirBlock block)
Takes a block owned by the caller and inserts it at pos to the given region.
This is an expensive operation that linearly scans the region, prefer insertAfter/Before instead.
Definition at line 341 of file IR.cpp.
References unwrap().
Referenced by mlirRegionIsNull().
mlirRegionInsertOwnedBlockAfter()
void mlirRegionInsertOwnedBlockAfter (MlirRegion region, MlirBlock reference, MlirBlock block)
Takes a block owned by the caller and inserts it after the (non-owned) reference block in the given region.
The reference block must belong to the region. If the reference block is null, prepends the block to the region.
Definition at line 347 of file IR.cpp.
References mlir::Region::begin(), mlir::Region::getBlocks(), mlirBlockIsNull(), and unwrap().
Referenced by mlirRegionIsNull().
mlirRegionInsertOwnedBlockBefore()
void mlirRegionInsertOwnedBlockBefore (MlirRegion region, MlirBlock reference, MlirBlock block)
Takes a block owned by the caller and inserts it before the (non-owned) reference block in the given region.
The reference block must belong to the region. If the reference block is null, appends the block to the region.
Definition at line 361 of file IR.cpp.
References mlirBlockIsNull(), mlirRegionAppendOwnedBlock(), and unwrap().
Referenced by mlirRegionIsNull().
mlirTypeDump()
void mlirTypeDump (MlirType type)
Prints the type to the standard error stream.
Definition at line 523 of file IR.cpp.
References unwrap().
Referenced by mlirTypeIsNull(), and mlir::python::PyType::operator==().
mlirTypeEqual()
int mlirTypeEqual (MlirType t1, MlirType t2)
Checks if two types are equal.
Definition at line 515 of file IR.cpp.
References unwrap().
Referenced by mlirTypeIsNull(), and mlir::python::PyType::operator==().
mlirTypeGetContext()
MlirContext mlirTypeGetContext (MlirType type)
Gets the context that a type was created with.
Definition at line 511 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirValueIsNull(), and mlir::python::PyType::operator==().
mlirTypeParseGet()
MlirType mlirTypeParseGet (MlirContext context, const char * type)
Parses a type.
The type is owned by the context.
Definition at line 507 of file IR.cpp.
References mlir::parseType(), unwrap(), and wrap().
Referenced by mlirValueIsNull(), and mlir::python::PyType::operator==().
mlirTypePrint()
void mlirTypePrint (MlirType type, MlirStringCallback callback, void * userData)
Prints a location by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 517 of file IR.cpp.
References mlir::Diagnostic::print(), and unwrap().
Referenced by mlirTypeIsNull(), and mlir::python::PyType::operator==().
mlirValueDump()
void mlirValueDump (MlirValue value)
Prints the value to the standard error stream.
Definition at line 494 of file IR.cpp.
References unwrap().
Referenced by mlirValueIsNull(), and mlir::python::PyType::operator==().
mlirValueGetType()
MlirType mlirValueGetType (MlirValue value)
Returns the type of the value.
Definition at line 490 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirValueIsNull(), and mlir::python::PyType::operator==().
mlirValueIsABlockArgument()
int mlirValueIsABlockArgument (MlirValue value)
Returns 1 if the value is a block argument, 0 otherwise.
Definition at line 460 of file IR.cpp.
References unwrap().
Referenced by mlirValueIsNull(), and mlir::python::PyType::operator==().
mlirValueIsAOpResult()
int mlirValueIsAOpResult (MlirValue value)
Returns 1 if the value is an operation result, 0 otherwise.
Definition at line 464 of file IR.cpp.
References unwrap().
Referenced by mlirValueIsNull(), and mlir::python::PyType::operator==().
mlirValuePrint()
void mlirValuePrint (MlirValue value, MlirStringCallback callback, void * userData)
Prints a value by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 496 of file IR.cpp.
References mlir::Diagnostic::print(), and unwrap().
Referenced by mlirValueIsNull(), and mlir::python::PyType::operator==().