MLIR: lib/Dialect/Linalg/Transforms/Loops.cpp File Reference
Loops.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Affine/EDSC/Intrinsics.h"
#include "mlir/Dialect/Linalg/EDSC/FoldedIntrinsics.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/SCF/EDSC/Builders.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/FoldUtils.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/TypeSwitch.h"
Classes
struct InputAndOutputIndices
Functions
static SmallVector< Value, 8 > makeCanonicalAffineApplies (OpBuilder &b, Location loc, AffineMap map, ArrayRef< Value > vals)
static SmallVector< Value, 4 > permuteIvs (ArrayRef< Value > ivs, Optional< AffineMap > permutation)
template<typename IndexedValueType , typename OpType >
static void inlineRegionAndEmitStore (OpType op, ArrayRef< Value > indexedValues, ArrayRef< SmallVector< Value, 8 >> indexing, ArrayRef< Value > outputBuffers)
template<typename SingleInputPoolingOp >
static InputAndOutputIndices getInputAndOutputIndices (ArrayRef< Value > allIvs, SingleInputPoolingOp op)
template<typename IndexedValueType >
static void emitScalarImplementation (ArrayRef< Value > allIvs, LinalgOp linalgOp)
Emits the MLIR for the scalar part of the generic op by:
template<typename IndexedValueType >
static void emitScalarImplementation (ArrayRef< Value > allIvs, CopyOp copyOp)
template<typename IndexedValueType >
static void emitScalarImplementation (ArrayRef< Value > allIvs, FillOp fillOp)
template<typename IndexedValueType >
Value getPaddedInput (Value input, ArrayRef< Value > indices, ArrayRef< int > skipPadding, Value padValue)
static bool hasPadding (ConvOp convOp)
Returns true is convOp has a non-zero padding.
template<typename IndexedValueType >
static void emitScalarImplementation (ArrayRef< Value > allIvs, ConvOp convOp)
template<typename PoolingOp >
static bool hasPadding (PoolingOp poolingOp)
template<typename IndexedValueType , typename PoolingOp >
static Value getPoolingInput (PoolingOp op, ArrayRef< Value > inputIndices)
template<typename IndexedValueType , typename OpType >
void emitPoolingMinMaxScalarImplementation (ArrayRef< Value > allIvs, OpType op)
template<typename IndexedValueType >
static void emitScalarImplementation (ArrayRef< Value > allIvs, PoolingMaxOp op)
template<typename IndexedValueType >
static void emitScalarImplementation (ArrayRef< Value > allIvs, PoolingMinOp op)
template<typename IndexedValueType >
static void emitScalarImplementation (ArrayRef< Value > allIvs, PoolingSumOp op)
template<typename IndexedValueType >
static void emitScalarImplementation (ArrayRef< Value > allIvs, IndexedGenericOp indexedGenericOp)
Emits the MLIR for the scalar part of the indexed generic op by:
template<typename LoopTy >
static Optional< LinalgLoops > linalgOpToLoopsImpl (Operation *op, OpBuilder &builder)
template<typename LoopType >
static void lowerLinalgToLoopsImpl (FuncOp funcOp, MLIRContext *context)
template Optional< LinalgLoops > mlir::linalg::linalgLowerOpToLoops< scf::ForOp > (OpBuilder &builder, Operation *op)
template Optional< LinalgLoops > mlir::linalg::linalgLowerOpToLoops< scf::ParallelOp > (OpBuilder &builder, Operation *op)
Function Documentation
emitPoolingMinMaxScalarImplementation()
template<typename IndexedValueType , typename OpType > void emitPoolingMinMaxScalarImplementation (ArrayRef< Value > allIvs, OpType op)
Definition at line 403 of file Loops.cpp.
References getInputAndOutputIndices(), InputAndOutputIndices::inputs, InputAndOutputIndices::outputs, mlir::edsc::op::sgt(), and mlir::edsc::op::slt().
emitScalarImplementation() [1/8]
template<typename IndexedValueType > static void emitScalarImplementation (ArrayRef< Value > allIvs, LinalgOp linalgOp) static
Emits the MLIR for the scalar part of the generic op by:
Emitting load ops for each input and output view in order. This is achieved by applying the appropriate input or output map to the enclosing induction variables.
Emitting a call to op.fun() that takes as arguments the scalars from point 1. above.
Emitting store ops to store the results of 2. to the output views.
An example output may resemble:
scf.for %i = %c0 to %0 step %c1 {
  scf.for %j = %c0 to %1 step %c1 {
    scf.for %k = %c0 to %4 step %c1 {
      %11 = load %arg0[%i, %j] :
        memref<?x?xf32, stride_specification>
      %12 = load %arg1[%i, %j, %k] :
        memref<?x?x?xf32, stride_specification>
      %13 = load %arg2[%i, %k, %j] :
        memref<?x?x?xf32, stride_specification>
      %14:2 = call @foo(%11, %12, %13) : (f32, f32, f32) -> (f32, f32)
      store %14#0, %arg1[%i, %j, %k] :
        memref<?x?x?Xf32, stride_specification>
      store %14#1, %arg2[%i, %k, %j] :
        memref<?x?x?Xf32, stride_specification>
   }
  }
}
Definition at line 139 of file Loops.cpp.
References mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getLocation(), and makeCanonicalAffineApplies().
emitScalarImplementation() [2/8]
template<typename IndexedValueType > static void emitScalarImplementation (ArrayRef< Value > allIvs, CopyOp copyOp) static
Definition at line 193 of file Loops.cpp.
References permuteIvs().
emitScalarImplementation() [3/8]
template<typename IndexedValueType > static void emitScalarImplementation (ArrayRef< Value > allIvs, FillOp fillOp) static
Definition at line 214 of file Loops.cpp.
emitScalarImplementation() [4/8]
template<typename IndexedValueType > static void emitScalarImplementation (ArrayRef< Value > allIvs, ConvOp convOp) static
Definition at line 345 of file Loops.cpp.
References mlir::Type::cast(), mlir::edsc::ScopedContext::getBuilderRef(), getElementType(), mlir::edsc::ScopedContext::getLocation(), mlir::AffineMapAttr::getValue(), hasPadding(), and makeCanonicalAffineApplies().
emitScalarImplementation() [5/8]
template<typename IndexedValueType > static void emitScalarImplementation (ArrayRef< Value > allIvs, PoolingMaxOp op) static
Definition at line 418 of file Loops.cpp.
emitScalarImplementation() [6/8]
template<typename IndexedValueType > static void emitScalarImplementation (ArrayRef< Value > allIvs, PoolingMinOp op) static
Definition at line 424 of file Loops.cpp.
emitScalarImplementation() [7/8]
template<typename IndexedValueType > static void emitScalarImplementation (ArrayRef< Value > allIvs, PoolingSumOp op) static
Definition at line 430 of file Loops.cpp.
References getInputAndOutputIndices().
emitScalarImplementation() [8/8]
template<typename IndexedValueType > static void emitScalarImplementation (ArrayRef< Value > allIvs, IndexedGenericOp indexedGenericOp) static
Emits the MLIR for the scalar part of the indexed generic op by:
Emitting load ops for each input and output view in order. This is achieved by applying the appropriate input or output map to the enclosing induction variables.
Emitting a call to op.fun() that takes as arguments the induction variables and the scalars from point 1. above.
Emitting store ops to store the results of 2. to the output views.
An example output may resemble:
scf.for %i = %c0 to %0 step %c1 {
  scf.for %j = %c0 to %1 step %c1 {
    scf.for %k = %c0 to %4 step %c1 {
      %11 = load %arg0[%i, %j] :
        memref<?x?xf32, stride_specification>
      %12 = load %arg1[%i, %j, %k] :
        memref<?x?x?xf32, stride_specification>
      %13 = load %arg2[%i, %k, %j] :
        memref<?x?x?xf32, stride_specification>
      %14:2 = call @foo(%i, %j, %k, %11, %12, %13) :
        (index, index, index, f32, f32, f32) -> (f32, f32)
      store %14#0, %arg1[%i, %j, %k] :
        memref<?x?x?Xf32, stride_specification>
      store %14#1, %arg2[%i, %k, %j] :
        memref<?x?x?Xf32, stride_specification>
   }
  }
}
Definition at line 470 of file Loops.cpp.
References mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getLocation(), and makeCanonicalAffineApplies().
getInputAndOutputIndices()
template<typename SingleInputPoolingOp > static InputAndOutputIndices getInputAndOutputIndices (ArrayRef< Value > allIvs, SingleInputPoolingOp op) static
Definition at line 96 of file Loops.cpp.
References mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getLocation(), mlir::AffineMapAttr::getValue(), and makeCanonicalAffineApplies().
Referenced by emitPoolingMinMaxScalarImplementation(), and emitScalarImplementation().
getPaddedInput()
template<typename IndexedValueType > Value getPaddedInput (Value input, ArrayRef< Value > indices, ArrayRef< int > skipPadding, Value padValue)
Definition at line 230 of file Loops.cpp.
References mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::AffineMap::get(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), mlir::edsc::op::sge(), and mlir::edsc::op::slt().
getPoolingInput()
template<typename IndexedValueType , typename PoolingOp > static Value getPoolingInput (PoolingOp op, ArrayRef< Value > inputIndices) static
Definition at line 389 of file Loops.cpp.
References getElementType(), and hasPadding().
hasPadding() [1/2]
static bool hasPadding (ConvOp convOp) static
Returns true is convOp has a non-zero padding.
Definition at line 336 of file Loops.cpp.
Referenced by emitScalarImplementation(), and getPoolingInput().
hasPadding() [2/2]
template<typename PoolingOp > static bool hasPadding (PoolingOp poolingOp) static
Definition at line 380 of file Loops.cpp.
inlineRegionAndEmitStore()
template<typename IndexedValueType , typename OpType > static void inlineRegionAndEmitStore (OpType op, ArrayRef< Value > indexedValues, ArrayRef< SmallVector< Value, 8 >> indexing, ArrayRef< Value > outputBuffers) static
Definition at line 65 of file Loops.cpp.
References mlir::edsc::ScopedContext::getBuilderRef(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::BlockAndValueMapping::lookupOrDefault(), and mlir::BlockAndValueMapping::map().
linalgOpToLoopsImpl()
template<typename LoopTy > static Optional<LinalgLoops> linalgOpToLoopsImpl (Operation * op, OpBuilder & builder) static
Definition at line 518 of file Loops.cpp.
References mlir::concatAffineMaps(), mlir::Value::dyn_cast(), mlir::linalg::emitLoopRanges(), mlir::PatternRewriter::eraseOp(), mlir::failure(), mlir::Operation::getLoc(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), getShape(), mlir::AffineMapAttr::getValue(), and mlir::success().
lowerLinalgToLoopsImpl()
template<typename LoopType > static void lowerLinalgToLoopsImpl (FuncOp funcOp, MLIRContext * context) static
Definition at line 589 of file Loops.cpp.
References mlir::applyPatternsAndFoldGreedily(), mlir::AffineExpr::dyn_cast(), mlir::failure(), mlir::Operation::getOperand(), mlir::OwningRewritePatternList::insert(), mlir::PatternRewriter::replaceOp(), mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
makeCanonicalAffineApplies()
static SmallVector<Value, 8> makeCanonicalAffineApplies (OpBuilder & b, Location loc, AffineMap map, ArrayRef< Value > vals) static
Definition at line 36 of file Loops.cpp.
References mlir::canonicalizeMapAndOperands(), mlir::AffineMap::get(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResults(), and mlir::AffineMap::isEmpty().
Referenced by emitScalarImplementation(), and getInputAndOutputIndices().
mlir::linalg::linalgLowerOpToLoops< scf::ForOp >()
template Optional<LinalgLoops> mlir::linalg::linalgLowerOpToLoops< scf::ForOp > (OpBuilder & builder, Operation * op)
mlir::linalg::linalgLowerOpToLoops< scf::ParallelOp >()
template Optional<LinalgLoops> mlir::linalg::linalgLowerOpToLoops< scf::ParallelOp > (OpBuilder & builder, Operation * op)
permuteIvs()
static SmallVector<Value, 4> permuteIvs (ArrayRef< Value > ivs, Optional< AffineMap > permutation) static
Definition at line 56 of file Loops.cpp.
References applyMapToValues(), mlir::edsc::ScopedContext::getBuilderRef(), and mlir::edsc::ScopedContext::getLocation().
Referenced by emitScalarImplementation().