MLIR: lib/Conversion/PDLToPDLInterp/PDLToPDLInterp.cpp File Reference
PDLToPDLInterp.cpp File Reference
#include "mlir/Conversion/PDLToPDLInterp/PDLToPDLInterp.h"
#include "../PassDetail.h"
#include "PredicateTree.h"
#include "mlir/Dialect/PDL/IR/PDL.h"
#include "mlir/Dialect/PDL/IR/PDLTypes.h"
#include "mlir/Dialect/PDLInterp/IR/PDLInterp.h"
#include "mlir/Pass/Pass.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/ScopedHashTable.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/TypeSwitch.h"
Functions
template<typename OpT , typename PredT , typename ValT = typename PredT::KeyTy>
static void createSwitchOp (Value val, Block *defaultDest, OpBuilder &builder, ArrayRef< std::pair< Qualifier *, Block *>> dests)
Function Documentation
createSwitchOp()
template<typename OpT , typename PredT , typename ValT = typename PredT::KeyTy> static void createSwitchOp (Value val, Block * defaultDest, OpBuilder & builder, ArrayRef< std::pair< Qualifier *, Block *>> dests) static
Definition at line 335 of file PDLToPDLInterp.cpp.
References mlir::OpBuilder::atBlockBegin(), mlir::pdl_to_pdl_interp::Predicates::AttributeQuestion, mlir::FuncOp::create(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::Operation::getBlock(), mlir::ModuleOp::getBody(), mlir::Builder::getFunctionType(), mlir::pdl_to_pdl_interp::Qualifier::getKind(), mlir::Value::getLoc(), mlir::OpState::getLoc(), mlir::ModuleOp::getOps(), mlir::Builder::getType(), mlir::Value::getUses(), mlir::Operation::isBeforeInBlock(), mlir::pdl_to_pdl_interp::Predicates::OperandCountQuestion, mlir::pdl_to_pdl_interp::Predicates::OperationNameQuestion, mlir::pdl_to_pdl_interp::Predicates::ResultCountQuestion, mlir::pdl_to_pdl_interp::Predicates::TypeQuestion, and mlir::pdl_to_pdl_interp::Predicates::UnsignedAnswer.