MLIR: lib/ExecutionEngine/SparseUtils.cpp File Reference
SparseUtils.cpp File Reference
#include <cctype>
#include <cinttypes>
#include <cstdio>
#include <cstdlib>
#include <cstring>
Functions
static char * toLower (char *token)
static void readHeader (FILE *file, char *name, uint64_t *m, uint64_t *n, uint64_t *nnz)
static void readItem (FILE *file, char *name, uint64_t *i, uint64_t *j, double *d)
void openMatrix (char *filename, uint64_t *mbase, uint64_t *mdata, int64_t moff, uint64_t *nbase, uint64_t *ndata, int64_t noff, uint64_t *nnzbase, uint64_t *nnzdata, int64_t nnzoff)
void readMatrixItem (uint64_t *ibase, uint64_t *idata, int64_t ioff, uint64_t *jbase, uint64_t *jdata, int64_t joff, double *dbase, double *ddata, int64_t doff)
void closeMatrix ()
char * getMatrix (uint64_t id)
Variables
static FILE * sparseFile = nullptr
static char * sparseFilename = nullptr
Function Documentation
closeMatrix()
void closeMatrix ()
Definition at line 155 of file SparseUtils.cpp.
References sparseFile, and sparseFilename.
getMatrix()
char* getMatrix (uint64_t id)
Definition at line 167 of file SparseUtils.cpp.
openMatrix()
void openMatrix (char * filename, uint64_t * mbase, uint64_t * mdata, int64_t moff, uint64_t * nbase, uint64_t * ndata, int64_t noff, uint64_t * nnzbase, uint64_t * nnzdata, int64_t nnzoff)
Definition at line 127 of file SparseUtils.cpp.
References readHeader(), sparseFile, and sparseFilename.
readHeader()
static void readHeader (FILE * file, char * name, uint64_t * m, uint64_t * n, uint64_t * nnz) static
Definition at line 41 of file SparseUtils.cpp.
References toLower().
Referenced by openMatrix().
readItem()
static void readItem (FILE * file, char * name, uint64_t * i, uint64_t * j, double * d) static
Definition at line 81 of file SparseUtils.cpp.
Referenced by readMatrixItem().
readMatrixItem()
void readMatrixItem (uint64_t * ibase, uint64_t * idata, int64_t ioff, uint64_t * jbase, uint64_t * jdata, int64_t joff, double * dbase, double * ddata, int64_t doff)
Definition at line 145 of file SparseUtils.cpp.
References readItem(), sparseFile, and sparseFilename.
toLower()
static char* toLower (char * token) static
Definition at line 31 of file SparseUtils.cpp.
Referenced by readHeader().
Variable Documentation
sparseFile
FILE* sparseFile = nullptr static
Definition at line 124 of file SparseUtils.cpp.
Referenced by closeMatrix(), openMatrix(), and readMatrixItem().
sparseFilename
char* sparseFilename = nullptr static
Definition at line 125 of file SparseUtils.cpp.
Referenced by closeMatrix(), openMatrix(), and readMatrixItem().