MLIR: lib/CAPI/Standard/StandardDialect.cpp File Reference
StandardDialect.cpp File Reference
#include "mlir-c/StandardDialect.h"
#include "mlir-c/IR.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Support.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
Functions
void mlirContextRegisterStandardDialect (MlirContext context)
Registers the Standard dialect with the given context.
MlirDialect mlirContextLoadStandardDialect (MlirContext context)
Loads the Standard dialect into the given context.
MlirStringRef mlirStandardDialectGetNamespace ()
Returns the namespace of the Standard dialect, suitable for loading it.
Function Documentation
mlirContextLoadStandardDialect()
MlirDialect mlirContextLoadStandardDialect (MlirContext context)
Loads the Standard dialect into the given context.
The dialect does not have to be registered in advance.
Definition at line 19 of file StandardDialect.cpp.
References unwrap(), and wrap().
mlirContextRegisterStandardDialect()
void mlirContextRegisterStandardDialect (MlirContext context)
Registers the Standard dialect with the given context.
This allows the dialect to be loaded dynamically if needed when parsing.
Definition at line 15 of file StandardDialect.cpp.
References unwrap().
mlirStandardDialectGetNamespace()
MlirStringRef mlirStandardDialectGetNamespace ()
Returns the namespace of the Standard dialect, suitable for loading it.
Definition at line 23 of file StandardDialect.cpp.
References wrap().