MLIR: mlir::GPUIndexIntrinsicOpLowering< Op, XOp, YOp, ZOp > Struct Template Reference
mlir::GPUIndexIntrinsicOpLowering< Op, XOp, YOp, ZOp > Struct Template Reference
#include "Conversion/GPUCommon/IndexIntrinsicsOpLowering.h"
Public Member Functions
GPUIndexIntrinsicOpLowering (LLVMTypeConverter &typeConverter)
LogicalResult matchAndRewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const override
Hook for derived classes to implement combined matching and rewriting.
Public Member Functions inherited from mlir::ConvertToLLVMPattern
ConvertToLLVMPattern (StringRef rootOpName, MLIRContext *context, LLVMTypeConverter &typeConverter, PatternBenefit benefit=1)
Public Member Functions inherited from mlir::ConversionPattern
virtual void rewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement rewriting.
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match and rewrite the IR root at the specified operation.
TypeConverter * getTypeConverter () const
Return the type converter held by this pattern, or nullptr if the pattern does not require type conversion.
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
virtual LogicalResult match (Operation *op) const
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
Additional Inherited Members
Protected Member Functions inherited from mlir::ConvertToLLVMPattern
LLVM::LLVMDialect & getDialect () const
Returns the LLVM dialect.
LLVM::LLVMType getIndexType () const
Gets the MLIR type wrapping the LLVM integer type whose bit width is defined by the used type converter.
LLVM::LLVMType getIntPtrType (unsigned addressSpace=0) const
Gets the MLIR type wrapping the LLVM integer type whose bit width corresponds to that of a LLVM pointer type.
LLVM::LLVMType getVoidType () const
Gets the MLIR type wrapping the LLVM void type.
LLVM::LLVMType getVoidPtrType () const
Get the MLIR type wrapping the LLVM i8* type.
Value createIndexConstant (ConversionPatternRewriter &builder, Location loc, uint64_t value) const
Create an LLVM dialect operation defining the given index constant.
Value linearizeSubscripts (ConversionPatternRewriter &builder, Location loc, ArrayRef< Value > indices, ArrayRef< Value > allocSizes) const
Value getStridedElementPtr (Location loc, Type elementTypePtr, Value descriptor, ValueRange indices, ArrayRef< int64_t > strides, int64_t offset, ConversionPatternRewriter &rewriter) const
Value getDataPtr (Location loc, MemRefType type, Value memRefDesc, ValueRange indices, ConversionPatternRewriter &rewriter) const
Type getElementPtrType (MemRefType type) const
Returns the type of a pointer to an element of the memref.
void getMemRefDescriptorSizes (Location loc, MemRefType memRefType, ArrayRef< Value > dynSizes, ConversionPatternRewriter &rewriter, SmallVectorImpl< Value > &sizes) const
Determines sizes to be used in the memref descriptor.
Value getSizeInBytes (Location loc, Type type, ConversionPatternRewriter &rewriter) const
Computes the size of type in bytes.
Value getNumElements (Location loc, ArrayRef< Value > shape, ConversionPatternRewriter &rewriter) const
Computes total number of elements for the given shape.
Value getCumulativeSizeInBytes (Location loc, Type elementType, ArrayRef< Value > shape, ConversionPatternRewriter &rewriter) const
Computes total size in bytes of to store the given shape.
MemRefDescriptor createMemRefDescriptor (Location loc, MemRefType memRefType, Value allocatedPtr, Value alignedPtr, uint64_t offset, ArrayRef< int64_t > strides, ArrayRef< Value > sizes, ConversionPatternRewriter &rewriter) const
Creates and populates the memref descriptor struct given all its fields.
Protected Member Functions inherited from mlir::ConversionPattern
ConversionPattern (StringRef rootName, PatternBenefit benefit, TypeConverter &typeConverter, MLIRContext *ctx)
Construct a conversion pattern that matches an operation with the given root name.
ConversionPattern (PatternBenefit benefit, TypeConverter &typeConverter, MatchAnyOpTypeTag tag)
Construct a conversion pattern that matches any operation type.
Protected Member Functions inherited from mlir::RewritePattern
virtual void anchor ()
An anchor for the virtual table.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a pattern with a certain benefit that matches any operation type.
Pattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a pattern that may match any operation type.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Protected Attributes inherited from mlir::ConvertToLLVMPattern
LLVMTypeConverter & typeConverter
Reference to the type converter, with potential extensions.
Protected Attributes inherited from mlir::ConversionPattern
TypeConverter * typeConverter = nullptr
An optional type converter for use by this pattern.
Detailed Description
template<typename Op, typename XOp, typename YOp, typename ZOp>
struct mlir::GPUIndexIntrinsicOpLowering< Op, XOp, YOp, ZOp >
Definition at line 24 of file IndexIntrinsicsOpLowering.h.
Constructor & Destructor Documentation
GPUIndexIntrinsicOpLowering()
template<typename Op , typename XOp , typename YOp , typename ZOp > mlir::GPUIndexIntrinsicOpLowering< Op, XOp, YOp, ZOp >::GPUIndexIntrinsicOpLowering (LLVMTypeConverter & typeConverter) inline explicit
Definition at line 38 of file IndexIntrinsicsOpLowering.h.
Member Function Documentation
matchAndRewrite()
template<typename Op , typename XOp , typename YOp , typename ZOp > LogicalResult mlir::GPUIndexIntrinsicOpLowering< Op, XOp, YOp, ZOp >::matchAndRewrite (Operation * op, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) const inline override virtual
Hook for derived classes to implement combined matching and rewriting.
Reimplemented from mlir::ConversionPattern.
Definition at line 46 of file IndexIntrinsicsOpLowering.h.
References mlir::PatternRewriter::create(), mlir::failure(), mlir::Builder::getContext(), mlir::LLVM::LLVMType::getInt32Ty(), mlir::LLVM::LLVMType::getIntNTy(), mlir::Operation::getLoc(), mlir::ConversionPatternRewriter::replaceOp(), and mlir::success().
The documentation for this struct was generated from the following file:
lib/Conversion/GPUCommon/IndexIntrinsicsOpLowering.h